### ISSUE TITLE
[Doc] Broken link: Get started > Next Steps

### ISSUE THREAD

**Issue by htalat** [AnswerDotAI/fasthtml#100]
[Getting started](https://docs.fastht.ml/#next-steps) points to [FastHTML Examples Repo on GitHub](https://github.com/AnswerDotAI/fasthtml-examples) that does not exist

I did notice there's a https://github.com/AnswerDotAI/fasthtml-example

**Comment by johnowhitaker** [comment]
Thanks, fixed
