### ISSUE TITLE
Typo in code block on website

### ISSUE THREAD

**Issue by wjbmattingly** [AnswerDotAI/fasthtml#101]
I'm just starting to test out the package and I already love it! I noticed a typo on the website, though, under BYO Blog:

<img width="852" alt="image" src="https://github.com/user-attachments/assets/b03a41bf-f7c6-4fea-9af7-b145796128e9">

I think this should be:

```python
from fasthtml import common as fh
```

and not:

```python
from fastapi import common as fh
```

**Comment by pydanny** [comment]
Thanks @wjbmattingly!

**Comment by wjbmattingly** [comment]
No problem!
