### ISSUE TITLE
svg support

### ISSUE THREAD

**Issue by arjunskumar** [AnswerDotAI/fasthtml#104]
could you provide an example code snippet to support svg ?
```
<h1>Simple SVG Image</h1>
<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg">
    <circle cx="100" cy="100" r="50" fill="blue" />
</svg>
```

**Comment by johnowhitaker** [comment]
Here's a bit of magic:

```python
from fasthtml.common import *
from fasthtml.components import Circle

app, rt = fast_app()


@rt('/')
def get():
  return Titled(
      'Simple SVG Image',
      Svg(Circle(cx='100', cy='100', r='50', fill='blue'),
          width='200',
          height='200',
          xmlns='http://www.w3.org/2000/svg'))


serve()
```

We don't define `Circle` anywhere. But if you want a <circle> tag to use in an SVG, just import `Circle` from fasthtml.components ! So the above works fine.

**Comment by johnowhitaker** [comment]
![image](https://github.com/user-attachments/assets/1907ee7c-b86f-4dbc-ba25-3b892f584beb)

**Comment by johnowhitaker** [comment]
If you want all the SVG you can `from fasthtml.svg import *` (see https://github.com/AnswerDotAI/fasthtml/blob/6e8e8adf9839474b2ee3807d1e1876c1414049b3/fasthtml/svg.py for the list) and then any SVG should work*

*I think, I don't know much about SVGs :)
