### ISSUE TITLE
Not getting hot reload (watcher works) with python or uvicorn

### ISSUE THREAD

**Issue by altryne** [AnswerDotAI/fasthtml#105]
Tried on multiple browsers (Chrome, Arc), it seems that the changes register, but I am not getting hot reload like examples show, not sure how to debug or what I'm doing wrong, was under the impression that this was built in. 

Running the examples as is
```
if __name__ == '__main__': uvicorn.run("main:app", host='0.0.0.0', port=8000, reload=True)
```

and seeing in output: 

```
WARNING:  WatchFiles detected changes in 'main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [26548]
INFO:     Started server process [26590]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```

**Comment by johnowhitaker** [comment]
You'll still need to refresh the page in your browser to see changes unless you're using `FastHTMLWithLiveReload` (see https://docs.fastht.ml/ref/live_reload.html)

**Comment by altryne** [comment]
I saw this after I posted the issue, this is now in my code
![CleanShot 2024-07-30 at 15 25 59@2x](https://github.com/user-attachments/assets/34c3845a-af77-4421-8cb4-4d04658990df)

and then 
```

serve()
```
at the end

and I ran it with both `python main.py` and with uvicorn: main:app --reload and it doesn't seem to make any different, I don't see any new events hitting the browser network tab 🤔

**Comment by altryne** [comment]
oh 🤦‍♂️ I declared the app twice, and this is why this whole thing didn't work, posting here in case someone else will run into this like I did.
