### ISSUE TITLE
how to use fasthtml under apache2 running on ubuntu

### ISSUE THREAD

**Issue by katahdin0** [AnswerDotAI/fasthtml#107]
really a newbie question, but I am struggling with this, I tried many things, even added a line to print "Content-Type" and nothing works, other things are working fine (I put up a perl cgi script, php etc. they are working fine.

I am clearly not following something, so any help would be much appreciated (and maybe a section on  apache2/ubuntu or nginx/ubuntu could be added ?

**Comment by yangcheng** [comment]
fasthtml use uvicorn and similar to fastapi setup. I think search for apache + uvicorn or apache + fastapi can give you some idea.

**Comment by katahdin0** [comment]
Thanks, that was helpful, reading up on some info now

**Comment by pydanny** [comment]
> really a newbie question

All questions are good questions!

FastHTML is an ASGI app that uses the `uvicorn` library for local development. Fortunately for us, uvicorn includes deployment instructions in their documentation. 😄 

https://www.uvicorn.org/deployment/
