### ISSUE TITLE
https://docs.fastht.ml/tutorials/by_example.html refers to port 8000

### ISSUE THREAD

**Issue by kieranshanley** [AnswerDotAI/fasthtml#111]
When you run a fasthtml app the default port seems to be port 5001. The tutorials by_example uses port 8000 (previous default ?). This could be very confusing to a new starter so worth updating quickly.

**Comment by johnowhitaker** [comment]
If you run it with `uvicorn app:app --reload` (which that tutorial uses) it'll be 8000 by default, I'll think about how best to add a note that `serve()` uses a different default.
