### ISSUE TITLE
Allow for `Any` or `FT` as return type of routes

### ISSUE THREAD

**Issue by santigandolfo** [AnswerDotAI/fasthtml#112]
I'm play with FastHTML, and one of the things that I tend to to in my new projects is setup ruff with ANN (flake8-annotations)
I've been trying to add a return type to the tutorials `hello world` rout, but I can't seem to be able to define one that doesn't generate an `Internal Server Error`.

For example if I set it as `any` or `Div`:

```python
from fasthtml import Div
from fasthtml import P
from fasthtml.fastapp import fast_app
from fasthtml.fastapp import serve

app, rt = fast_app()


@rt("/")
def get() -> any:
    return Div(P("Hello World!"), hx_get="/change")


serve()
```

I get the errors:
```
TypeError: 'FT' object is not callable
```
or
```
TypeError: 'bool' object is not callable
```

I've tried with other types (FT, Html, etc) but all of them return an error similar to the previous ones.

**Comment by jph00** [comment]
Good point! Fixed in main - you can now use `FT` or `Any` as the return type.
