### ISSUE TITLE
"watch intro video" link is broken on https://fastht.ml/, it links to https://fastht.ml/#

### ISSUE THREAD

**Issue by yangcheng** [AnswerDotAI/fasthtml#114]
I have been looking forward for a framework like this, pure python but allows more customization than streamlit and gradio. Thanks so much for creating the project!

When I click the watch intro , nothing happens. then I realize the href is probably wrong. See the attached screenshot. 

![Screenshot 2024-07-31 at 10 25 14 AM](https://github.com/user-attachments/assets/72b83697-5426-4ed0-9b5c-876b2dd25517)

**Comment by jph00** [comment]
Video link uses JS to open in an iframe.
