### ISSUE TITLE
support database URIs

### ISSUE THREAD

**Issue by phiweger** [AnswerDotAI/fasthtml#116]
Awesome effort! From the source code of the `fast_app` fn and `Database` object it seems only sqlite is supported ATM. It would be helpful if database URIs were supported, eg when hosting a (postgres) database remotely. That includes parsing the authentication data in the URI etc. Thanks!

**Comment by jph00** [comment]
Yup more DBs will be added over time.

**Comment by jackbravo** [comment]
Adding this link just for reference: https://github.com/AnswerDotAI/fastsql which is the SQLAlchemy wrapper with which other database can be supported.
