### ISSUE TITLE
ModuleNotFoundError: No module named 'fasthtml'

### ISSUE THREAD

**Issue by dhavalcodes** [AnswerDotAI/fasthtml#118]
Getting the error: 

> 
>     from fasthtml.common import * ModuleNotFoundError: No module named 'fasthtml'
>     
>     `from fasthtml.common import *

from running `python3 main.py `which contains:
```
app,rt = fast_app()

@rt('/')
def get(): return Div(P('Hello World!'), hx_get="/change")

serve()`
```

Previously was getting serve() is not recognized errors. 

I used `pip3 install python-fasthtml` in my mac env and in a venv.

**Comment by pydanny** [comment]
@dhavalcodes, which version of Python are you on? You can check with `python -V`. Ideally you should be running 3.10 or higher.

**Comment by dhavalcodes** [comment]
Got it working - this was the issue. Thank you! o
