### ISSUE TITLE
Are there any plan in roadmap to create a SaaS template?

### ISSUE THREAD

**Issue by INF800** [AnswerDotAI/fasthtml#121]
For example, Wasp lang has https://opensaas.sh/ and FastAPI has https://github.com/tiangolo/full-stack-fastapi-template.

It would be nice to have a similar template! (Helps a ton).

Please let me know if there are any plans to build such template, happy to make some significant contributions!

Or is it too early for FastHTML to start building such templates?

**Comment by INF800** [comment]
Some other opensource SaaS templates which we can use as reference:

- Ruby on rails: https://bullettrain.co/
- Svelte: https://saasstarter.work/

**Comment by jph00** [comment]
There's much less of a need for such a template with FastHTML - e.g. as I read through the features of bullettrain.co I noticed that most of them are redundant.

I think the first step is to build out some more complete applications, and after that factor out any common functionality once we're happy with the design.
