### ISSUE TITLE
Trying to understand the reason of using objects for html

### ISSUE THREAD

**Issue by ddahan** [AnswerDotAI/fasthtml#124]
Hi there.
In React you can do this:

```ts
const ItemList = ({ items }) => {
  return (
    <ul>
      {items.map((item, index) => (
        <li key={index}>{item}</li>
      ))}
    </ul>
  );
};
```

While it allows to inject arbitrary html using code, it preserves the global structure of html, keeping the whole thing pretty much readable, especially because html tags are visible, and the whole indentation represents the structure of the document.

Why would a Python equivalent not suitable, with fasthtml?

While I understand the benefits of not using a templating language, I'm very sceptical about the readability of html, when it is written with Python objects, due to cognitive load to actually see how the code is structured.

Thanks for the explanations.

**Comment by johnowhitaker** [comment]
There is a lot of personal preference for things like this. I find for smaller stuff the Python version can be very readable and clear - e.g. your example might be one of:

```python
def ItemList(items):
    return Ul(*[Li(item) for item in items])

def ItemList(items):
    list_items = []
    for item in items:
        list_items.append(Li(item))
    return Ul(*list_items)

def ItemList(items):
    return Ul(
        *map(lambda item: Li(item), items)
    )
```

When you get to lots of nested elements with classes for styling and extra attributes it can be a little harder to follow (as can badly-written HTML to be fair). Still, you can refactor into smaller pieces that compose together and keep it manageable IMO.

**Comment by jph00** [comment]
The React version and the FastHTML version are pretty much identical, except that in React JSX provides some syntax sugar to hide the functional component.

**Comment by ddahan** [comment]
@jph00 it's very different to me, at least in terms of cognitive load, since the React version is written like html, with opening and closing tags. This implies you keep the same indentation and visualization than with html. Maybe the same syntax color with your editor, and so on.
In React case, it looks like html with interpolated JS, but with fasthtml, it's pure Python that does not look like html at all at first glance.

I'm not saying it's bad, just giving my single feedback on what it feels to me, and trying to understand if technically speaking, it could have look like more to the react version or not.

Thanks!
