### ISSUE TITLE
Events / Reactivity? How to do it with FastHTML/HTMX?

### ISSUE THREAD

**Issue by altryne** [AnswerDotAI/fasthtml#129]
Hey, as a frontend dev for a while, I'm trying to wrap my head around fastHTML and HTMX, and while I get the whole, click on this, it will replace that target with ajax via htmx, and that's fire, but sometimes, I want to update other parts of the ui, like a global counter, or a state or something. 

In frontend frameworks this is done via some sort of state management, either in JS session or a specific state, but with fastHTML I am not quite sure how to do something like, action -> htmx -> update one part of the UI but also get an event and update other parts of the UI after that. 

Any pointers on how you guys are thinking about this?

**Comment by vacmar01** [comment]
The 'hx-swap-oob' attribute might be interesting for what you try to do: https://htmx.org/attributes/hx-swap-oob/

But in general the thought process is completely different when using HTML/HTMX compared to a state driven reactive framework like React, Vue, Svelte etc. 

You explicitly state what parts of the DOM should be replaced by what when writing your return statements in the routing functions. If you want to update more than the target, have a look at the link I provided above.

**Comment by jph00** [comment]
I recommend reading this book to help learn this approach:

https://hypermedia.systems/
