### ISSUE TITLE
accordion demo render issue

### ISSUE THREAD

**Issue by ericfrederich** [AnswerDotAI/fasthtml#135]
On the [FastHTML website](https://fastht.ml/) there is an accordion demo.  When you expand all 3 of the items it renders out side of the box its in.

![fasthtml](https://github.com/user-attachments/assets/b2e44d4c-8d9c-4237-b106-5d7c656c1af5)

**Comment by jph00** [comment]
Thanks for noting! If anyone is interested in fixing this, the repo is here: https://github.com/answerDotAI/home-fasthtml/

One possible fix would be to change the component so it only opens one at a time. It might be nice to also replace the implementation with a self-contained surreal.js approach.

**Comment by Viddesh1** [comment]
Thanks for the information. I think below pull request resolve the same problem present in this github issue:

https://github.com/AnswerDotAI/home-fasthtml/pull/2

**Comment by rajbhoyar729** [comment]
@jph00  is this issue solved ??

**Comment by jph00** [comment]
there's an incomplete PR here https://github.com/AnswerDotAI/home-fasthtml/pull/2
