### ISSUE TITLE
Add discussions tab?

### ISSUE THREAD

**Issue by bryanwhiting** [AnswerDotAI/fasthtml#136]
is a discussions tab to this repo helpful or do you want to keep it to issues + discord?

**Comment by leejoramo-d51** [comment]
While I use Discord, I much prefer the forum style of GitHub's Discussion tab

**Comment by jph00** [comment]
We'll stick to discord, to avoid splitting the discussion.

**Comment by jph00** [comment]
OK I changed my mind :D Discussions are open now.
