### ISSUE TITLE
"Get started" tutorial fails right out of the gate due to missing endpoint

### ISSUE THREAD

**Issue by chriscarrollsmith** [AnswerDotAI/fasthtml#138]
So, the [Get Started](https://docs.fastht.ml/) tutorial gives this code:

```
from fasthtml.common import *

app,rt = fast_app()

@rt('/')
def get(): return Div(P('Hello World!'), hx_get="/change")

serve()
```

It then says, "Running the app with python main.py prints out a link to your running app: http://localhost:5001."

In fact, attempting to run the app with `python main.py` will do exactly nothing—not even print an informative error message. To actually run the app, you have to first perform the next step in the tutorial: add the '/change' endpoint.

So, I think two things need to happen: 

1) The instructions for this tutorial need to be corrected to clarify the order of operations;
2) It would be nice to have some informative error message print to the console if you can't run the app due to a missing endpoint.

Thanks for all your hard work on this!

**Comment by johnowhitaker** [comment]
Are you sure? I copied that code into a file and it ran as expected. Maybe you forgot to save the file before running and were instead executing an empty file?

**Comment by chriscarrollsmith** [comment]
> Are you sure? I copied that code into a file and it ran as expected. Maybe you forgot to save the file before running and were instead executing an empty file?

Huh. Okay, I could swear I tried saving and running it four or five times, but it's working now, so maybe you're right. Sorry about that.
