### ISSUE TITLE
Where is FT defined

### ISSUE THREAD

**Issue by learningpro** [AnswerDotAI/fasthtml#142]
python version 3.12
fasthtml is installed by  python3 setup.py install with main branch source code.

def fill_form(form:FT, obj)->FT:
                       ^^
NameError: name 'FT' is not defined. Did you mean: 'XT'?

when grep in fastcore folder,  there is neither FT defination

grep -r "FT" ./
                                      
grep: ./__pycache__/transform.cpython-312.pyc: binary file matches
grep: ./__pycache__/parallel.cpython-312.pyc: binary file matches
grep: ./__pycache__/net.cpython-312.pyc: binary file matches

**Comment by GirishKumarSharma** [comment]
[FT]: This could be a custom type or alias defined within the fasthtml library. To understand this better, you would need to look at the definition of FT within the library.

**Comment by jph00** [comment]
You'll need to update fastcore to the latest version. I'll double-check now the fasthtml deps are correct.
