### ISSUE TITLE
Need example to integrate with 3rd party react component such as gridjs

### ISSUE THREAD

**Issue by wgong** [AnswerDotAI/fasthtml#148]
Please give example on adding react component e.g, https://www.npmjs.com/package/gridjs-react

I like to port my streamlit app to fasthtml
Thanks

**Comment by juanfrank77** [comment]
Just an idea. Since Grid.js works with Vanilla, you can add the JS and CSS to the head of the HTML passing `default_hdrs=False` and then the appropriate headers [like this](https://docs.fastht.ml/tutorials/by_example.html#custom-scripts-and-styling)
