### ISSUE TITLE
Typo in docstring in live_reload.py

### ISSUE THREAD

**Issue by dishb** [AnswerDotAI/fasthtml#150]
https://github.com/AnswerDotAI/fasthtml/blob/3b992a001378149af6374e47e6f7caf24cd94e02/fasthtml/live_reload.py#L35

In the line above ^, there is a typo in the docstring. It should be "created" not "creaetd".

Nitpicky and minor issue but oh well 😅

**Comment by pydanny** [comment]
Nice catch! Want to create a PR and get attribution? 😄 

If not we'll do it, but we want lots more people on our contributor list.

**Comment by dishb** [comment]
Sure, I'll create one now. Wasn't sure if you guys wanted a PR or not for a trivial issue like this. :)

**Comment by dishb** [comment]
@pydanny - I finished setting up my clone of the repo locally but I'm not sure how I should fix the typos in docstrings without touching the `.py` files. I haven't found the docstrings/typos in the `nbs` folder.

Sorry - I'm new to Jupyter notebooks (never used them before).
