### ISSUE TITLE
Use mkdocs for documentation

### ISSUE THREAD

**Issue by gunungpw** [AnswerDotAI/fasthtml#154]
On the video there is signal that fasthtml will make custom docs for itself, but in my opinion it will be wise to use widely used docs/static site generator like mkdocs with material theme or sphinx with furo theme, so the outside contributor doesn't have to learn yet additional docs system,
I will contribute to the docs migration to mkdocs if this feel desirable.

**Comment by pydanny** [comment]
@gunungpw Thanks for the suggestion. I'm a fan of mkdocs and sphinx, especially the jupyter-book variant of the latter. 😄 

For reference, FastHTML isn't just documented with [nbdev](https://nbdev.fast.ai/), it is built with it in a literate programming style. So nbdev won't be going away. That means to use mkdocs (or sphinx) our docs would have a four-step (or more) workflow:

1. Write code/docs in nbdev
2. Export nbdev-markdown
3. Convert nbdev-markdown to mkdocs-markdown
4. Run mkdocs-markdown

All of the above need to run live and quickly to match current nbdev functionality.

Therefore, I think the scope of this is too large to be included in FastHTML. However, if you want to build a separate tool that handles this process I'll be happy to take a look. 😄
