### ISSUE TITLE
boolean htmx attributes don't work properly with ft

### ISSUE THREAD

**Issue by vacmar01** [AnswerDotAI/fasthtml#155]
HTMX attributes expect the string "true" to indicate that they are enabled (`hx-push-url="true"`), but ft translates something like `Form(hx_push_url=True)` to `<Form hx-push-url>` which doesn't work for HTMX attributes. 

Maybe we could check whether the html attribute belongs to htmx and then translate the python boolean to a string for these attributes when translating ft to html. 

An argument against it would be maybe that this change to `ft` is too specific for htmx, but that's something we could discuss. 

What do you think?

**Comment by jph00** [comment]
Use the string 'true', not the bool `True`.
