### ISSUE TITLE
How do I get custom script and style into the head, or specific position in the body

### ISSUE THREAD

**Issue by ravinsharma7** [AnswerDotAI/fasthtml#168]
I'm a big proponent of "Locality Of Behaviour", was trying to get fasthtml running with lit.dev webcomponents and tailwindcss using vitejs's backend integration. 
But I couldn't get the `<script>` tag to inject into the head. I modified the hello world example with a webcomponent. 

This is my main.py
```python
from fasthtml.common import *

hdrs = [
    Script(src="https://cdn.tailwindcss.com"),
    Script(src="http://localhost:5173/@vite/client")
]
app = FastHTMLWithLiveReload(hdrs=hdrs)
rt = app.route

SimpleGreeting = NotStr('<simple-greeting name="World"></simple-greeting>')

@rt('/')
def get(): 
  return SimpleGreeting

@rt('/change')
def get(): 
  return P('Nice to be here!')

serve() 
```

But I'm only getting this as output in the browser:
```html
<html>
  <head></head>
   <body>
      <simple-greeting name="World"></simple-greeting>
    </body>
</html>
```

I'm running the command using 
```bash
$ uvicorn main:app --reload
```

<br>
What am I doing wrong?

**Comment by jph00** [comment]
The extra stuff is only added if you return an `FT`, which `NotStr` isn't. Wrap it in a `Div()`.
