### ISSUE TITLE
Support FT in HTTPException handling

### ISSUE THREAD

**Issue by pydanny** [AnswerDotAI/fasthtml#175]
Was: 404 page handler doesn't render defaults. 

## Description

The issue is that exception handling occurs outside the routes. So the controls that add the header and footer HTML do not function. We could just paste in that stuff anyway, but let's see if we can have a better, easier solution. Our order of preference for the solution:

1. Specify it in docs without changing FastHTML
2. Easy-to-code change

```python
from fasthtml.common import *

async def not_found(request, exc):
    # return Response("Not Found", status_code=404)
    return HTMLResponse(
        to_xml(Titled("Not Found")),
        status_code=404,)


exception_handlers = {
    404: not_found
}

app = FastHTML(exception_handlers=exception_handlers)

@rt("/")
def get():
    return Titled("Hello, World!", "Hello, World!")


serve()
```

Result:

```html
<title>Not Found</title>

<main class="container">
  <h1>Not Found</h1>
</main>
```

It should include all the default page setup.

**Comment by jph00** [comment]
OK got this sorted. Not gonna say my code is pretty, but it does the job at least AFAICT.
