### ISSUE TITLE
Install Requirements

### ISSUE THREAD

**Issue by Kamek437** [AnswerDotAI/fasthtml#183]
I cannot install it into any of my conda environments, what are the requirements? This should be on the front page btw.

**Comment by synapticarbors** [comment]
FastHTML is up on conda-forge. You should be able to install it using either conda or mamba via `conda install -c conda-forge python-fasthtml`.

**Comment by jph00** [comment]
Oh nifty thanks @synapticarbors for letting us know! Do you know if that will be auto-updated as new releases are tagged?

**Comment by Kamek437** [comment]
Thanks guys, sorry for the trouble.

**Comment by synapticarbors** [comment]
@jph00 In theory a bot should automatically submit a PR for all new releases, but I'm seeing that it didn't for some reason. I'll manually update and then will follow releases here to see if the issue is persistent.

**Comment by jph00** [comment]
Many thanks Joshua -- if there's anything we can do at our end to help,
just let us know.
