### ISSUE TITLE
Raise warning if type is not passed

### ISSUE THREAD

**Issue by koaning** [AnswerDotAI/fasthtml#195]
I was banging my head to day because the slider inputs would not pass data to the backend. I could not figure out why. 

```python
@app.post("/slider-update")
def slider_update(data):
    print("updating chart")
    print(data)
    return Div(
        P(f"You have pressed the button {count} times."),
        generate_chart()
    )
```

Can you spot the issue?

This was the fix:

```python
@app.post("/slider-update")
def slider_update(data: dict):
    print("updating chart")
    print(data)
    return Div(
        P(f"You have pressed the button {count} times."),
        generate_chart()
    )
```

The type needed to be there, without it ... the dictionary is just none. A warning that the type information is missing would have really helped here.

**Comment by jph00** [comment]
Good point. Fixing that now.
