### ISSUE TITLE
sqlite -shm and -wal files cause extra uvicorn reloads

### ISSUE THREAD

**Issue by swyxio** [AnswerDotAI/fasthtml#200]
Hey folks, opening an issue instead of a PR because i'm not sure what the best solution is but I can clearly express the problem and you guys can figure out how you want to solve.

The immediate issue is that when i start a fasthtml project from scratch, the project loads 3 times:

```bash
$ python main.py 
Users found. 
Link: http://localhost:5001
INFO:     Will watch for changes in these directories: ['/Users/swyx/Documents/Work/ainews']
INFO:     Uvicorn running on http://0.0.0.0:5001 (Press CTRL+C to quit)
INFO:     Started reloader process [8628] using WatchFiles
Users found.
Users found.
INFO:     Started server process [8634]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```

the 3x "Users found." is the issue, and the cause is the creation of the sqlite files.

<img width="228" alt="image" src="https://github.com/user-attachments/assets/4de7968f-f5b9-4345-8d49-dcd398530293">

now uvicorn has [ignore/include](https://www.uvicorn.org/settings/#reloading-with-watchfiles) options that basically solve this issue, which fasthtml's `fast_app()` does not expose. 1) would you like to expose it, 2) would you want to adopt conventions for default?

the solution is probably like 2 lines of code, but just leaving to you to decide WHAT solution you want

**Comment by pydanny** [comment]
Hey @swyxio, I can't replicate your problem. Is it possible you can share a truncated version of your code?

**Comment by pydanny** [comment]
In the meantime, I'm adding your feature request. 😄

**Comment by pydanny** [comment]
@swyxio the `serve()` function now supports `reload_excludes`. It is documented [here](https://docs.fastht.ml/api/core.html#serve).
