### ISSUE TITLE
Adding a Title in headers doesn't change the title

### ISSUE THREAD

**Issue by milos-popovic** [AnswerDotAI/fasthtml#208]
Following code reproduces the problem:
```python
from fasthtml.common import *

app, rt = fast_app(hdrs=[Title('Test title')])

@ rt("/")
def get():
    return Div("Hello World")

serve(port=8082)
```

Results in following `<head>`:

```html
<head>
    <title>FastHTML page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <script src="https://unpkg.com/htmx.org@next/dist/htmx.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/answerdotai/surreal@1.3.0/surreal.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/gnat/css-scope-inline@main/script.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@latest/css/pico.min.css">
    <style>:root { --pico-font-size: 100%; }</style>
    <title>Test title</title>
    <style>
          .htmx-indicator{opacity:0}
          .htmx-request .htmx-indicator{opacity:1; transition: opacity 200ms ease-in;}
          .htmx-request.htmx-indicator{opacity:1; transition: opacity 200ms ease-in;}
    </style>
</head>
```

As you can see `<title>FastHTML page</title>` is not removed and thus, the page title keeps the  'FastHTML page' title.

Disabling default headers also doesn't remove the page title header:

```python
from fasthtml.common import *

app, rt = fast_app(hdrs=[Title('Test title')], default_hdrs=False)

@ rt("/")
def get():
    return Div("Hello World")

serve(port=8082)
```
results in:

```html
<head>
    <title>FastHTML page</title>
    <title>Test title</title>
</head>
```

Maybe there is a different way to change the title, as I can see that http://fastht.ml has a title properly set?

**Comment by Belaloui** [comment]
This is how the fastht.ml website sets the title: (adapted to your example)

```python
from fasthtml.common import *

app, rt = fast_app()

@ rt("/")
def get():
    return (Title("Test title"),
        Div("Hello World")
        )

serve(port=8082)
```

This solves the title issue in this example, but putting a title in `fast_app(hdrs=[Title('Test title')])` still results in an additional title tag in the generated html.

**Comment by ncoop57** [comment]
Yes, we handle title tags differently in fasthtml since each route can specify its own title. Behind the scenes we detect the title FastTag and move it into the header if it is returned in a route.

**Comment by milos-popovic** [comment]
Thanks, this did solve the problem!

For some reason I didn't think of including the title as part of the response. The approach makes sense, though I think it wouldn't hurt to make sure the header setting also works (overrides the default), for cases when you want to set the same title for all/most pages.

Should I close the issue, or leave it open in case you want to consider the header override also?

**Comment by jph00** [comment]
I'll close it, since it would be a bit tricky to support having titles defined in headers too.
