### ISSUE TITLE
fastht.ml is down says internal server error.

### ISSUE THREAD

**Issue by aerovenky** [AnswerDotAI/fasthtml#209]
Tried to raise a bug on https://github.com/AnswerDotAI/home-fasthtml, but bugs are locked there. 
So raising it here.
![image](https://github.com/user-attachments/assets/4b2dcd98-0a9c-4acc-9d83-26730cdbfa6e)

Happened on August 6th 10 PM IST (+05:30)

**Comment by aerovenky** [comment]
@jph00  FYI

**Comment by jph00** [comment]
Thanks - my bad; the dynamic weather widget didn't have an exception handler for issues with weather.gov!
