### ISSUE TITLE
Ease of setting cookies with typical FastHTML examples

### ISSUE THREAD

**Issue by onkarbhardwaj** [AnswerDotAI/fasthtml#212]
Right now, the demonstrated examples to set cookies is to operate on raw starlette requests and response. Can there be a simple example where a cookie is set to go with response shown in the examples like `Title(..), Div(..)`  if the cookie does not already exist in the request?

I am looking at something like
```
@rt.get("/")
def home(request):
      tuples = Title("Page Demo"), Div(H1('Hello, World'), P('Some text'), P('Some more text'))
      # construct a response object here with the above content and set cookie if cookie not present in the request
      # include the usual headers that the app was started with
      # return response
```

**Comment by onkarbhardwaj** [comment]
This is my current working example after digging through the codebase (sorry for not using `from fasthtml import *` ;) ).

```
import fasthtml.common as fhc
import fasthtml.fastapp as fhapp
import fasthtml.core as fhcore

# Code here to define app, etc.

@app.get("/")
def home():
    return (
            fhc.Title("Experiment"),
            fhcore.cookie("sayhi", "hi!", max_age=600),
            fhc.Main(
                fhc.Div(
                    fhc.Div("div1", id="div1"),
                    fhc.Div("div2", id="div2"),
                    fhc.Div("div3", id="div3"),
                    fhc.Div("div4", id="div4"),
                    cls='grid-container',
                )
            ),
        )

# Rest of the code ....
```

Also, @jph00 - Amazing work and thanks for empowering so many users. Such empathy, much wow! :)

**Comment by jph00** [comment]
Glad you got it sorted! BTW fasthtml.common already includes those other submodules, so you can just use `fhc` for everything.
