### ISSUE TITLE
"hx_target" not working

### ISSUE THREAD

**Issue by DaedlyKitten** [AnswerDotAI/fasthtml#216]
key word parameter hx_target is not working.
target_id works.

For example:

```
app,rt1 = fast_app(hdrs=(picolink,))

@rt1("/")
def get():
    return Main(Label('aaa',id='header'),
                Textarea("Hello World", hx_trigger='input',hx_target='header',hx_get='/save'),
                Button('dsada',target_id='header',hx_get='/save'),
                cls='container')

@rt1('/save',)
def get():
    return Label('changed',id='header')

serve(port=5001)
```

will only work when the hx_target='header' is changed to target_id='header'

**Comment by gautam-e** [comment]
@DaedlyKitten you probably need to change it to `hx_target='#header'`?
That is, don't forget the `#` when using `hx_target` so that it knows that it is an `id`.
