### ISSUE TITLE
Missing time element

### ISSUE THREAD

**Issue by pydanny** [AnswerDotAI/fasthtml#22]
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time

This may be a fastcore.xml issue.

**Comment by jph00** [comment]
Thanks for letting me know. BTW it's helpful to at-mention me on your issues/PRs so I get notified.

**Comment by jph00** [comment]
Oh also FYI it's fasthtml.components where the list of HTML elements comes from. I just went through and added all the non-deprecated ones listed on mozilla's docs.
