### ISSUE TITLE
Decorators don't get parameter values 

### ISSUE THREAD

**Issue by TomFaulkner** [AnswerDotAI/fasthtml#222]
I thought I would look into writing a validation decorator. I was surprised to see that parameters end up as None.

```python
from fasthtml.common import *

app = FastHTML()
messages = ["This is a message, which will get rendered as a paragraph"]

@app.get("/")
def home():
    return Main(H1('Messages'), 
        *[P(msg) for msg in messages],
        A("Link to Page 2 (to add messages)", href="/page2"))

@app.get("/page2")
def page2():
    return Main(
        Form(
            Input(type="text", name="a"),
            Input(type="number", name="b"),
            Button("Submit"),
            action="/",
            method="post"
        )
    )

def validator(f):
    def wrapper(*args, **kwargs):
        print(*args, **kwargs)
        return f(*args, **kwargs)
    return wrapper

@app.post("/")
@validator
def post(a: str, b: int):  # doesn't validate these
    print(f"Received {a=} {b=}")
    return home()

serve()
```

This will print `None, None` then the post function print also prints `None` for both values.

I would expect to see the values posted from the form. Without the decorator, this works as expected. I haven't looked into the source of the `.post` decorator method, but it seems like it is doing something that prevents my decorator from getting these parameters.

For what it's worth, `f.__annotations__` works as expected.

**Comment by TomFaulkner** [comment]
After seeing #188, I found that the parameters can take a dataclass or a Pydantic model, so my decorator function seems unnecessary. I am curious as to why this doesn't work though.

**Comment by Viddesh1** [comment]
Hello @TomFaulkner ,

```python
from functools import wraps # Added wraps imports

def validator(f):
    @wraps(f) # <-- I added a changed here
    def wrapper(*args, **kwargs):
        print(*args, **kwargs)
        return f(*args, **kwargs)
    return wrapper
```

```
hello -1
Received a='hello' b=-1
INFO:     127.0.0.1:46590 - "POST / HTTP/1.1" 200 OK
```

Thanks!
Viddesh

**Comment by TomFaulkner** [comment]
Thanks 

It's interesting that the wraps decorator helps here. I would have added it later, but my understanding is it just replaces the name of the function so it doesn't show up as wrapper.

Do you know why this helps? The decorator worked on other functions without it. I'm guessing there is a lookup done somewhere and the unwrapped decorator breaks this?

**Comment by jph00** [comment]
Yeah fasthtml has to be able to see all the annotations in order to inject the params.
