### ISSUE TITLE
triggering a function on button click

### ISSUE THREAD

**Issue by HassanJbara** [AnswerDotAI/fasthtml#223]
What I would like to do is update a value based on user input without having to send a request to a route, more like storing a state. I know that this is not the correct mentality of htmx, but I find it weird to be calling routes to save things on the client side. For example, I want to temporarily save user input for later, say, emails. You will have a form with input and buttons to call a route that looks like this:

```python
@rt("/store-email")
def post(email: str, session):
   session["email"] = email
   return Response(status_code=303, headers={"HX-Refresh": "true"})
```

I wish I could bind a function like this to the button:

```python
def store_email(email):
   app.user_email = email
```

This goes for any logic or state management in the app. If there is something I'm missing here I would appreciate some pointers, thank you.

**Comment by Viddesh1** [comment]
Hello @HassanJbara ,

Does this provide any help?

https://github.com/AnswerDotAI/fasthtml/issues/222

Regards!
Viddesh

**Comment by jph00** [comment]
You'd need to use js for this.
