### ISSUE TITLE
Session variables are a bit too aggressive

### ISSUE THREAD

**Issue by jbellis** [AnswerDotAI/fasthtml#224]
```
@app.get("/search")
def search(foo: UUID):
    if foo:
        session['foo'] = foo
```

Expected behavior: if there is an explicit `foo` query variable, it gets passed to the function.

Observed behavior: once `session['foo']` is set, it overrides the explicit query variable and there is no way to change it.

**Comment by jbellis** [comment]
Related (happy to open a separate issue if that's better): session auto-encode/decode is not symmetrical, it happily turns string parameters into UUID here but `session['foo'] = foo` will result in `TypeError: Object of type UUID is not JSON serializable`

**Comment by jph00** [comment]
A separate issue is better.

I don't see any particular reason that query vars should override session vars?

**Comment by jbellis** [comment]
It's more in keeping with the principle of least surprise for the explicitly passed parameter to override the magic implicit one.  And I think the example here is a good reason why that makes sense -- otherwise you have this one-way asymmetry in the semantics.

IMO of course.

**Comment by jph00** [comment]
Thanks for the followup. I will think on it for a bit :)

**Comment by jph00** [comment]
Upon reflection, I think it's actually bad to take params from the session at all, since the user could always delete the session and add a query string, those forging the session var. So I've removed that entirely now.
