### ISSUE TITLE
No precedence in view definitions

### ISSUE THREAD

**Issue by pydanny** [AnswerDotAI/fasthtml#23]
If I define this path:

```python
@app.get("/{slug/")
def markdown_page(slug: str)
    return ...
```

that will collide with this no matter if they are before or after each other:

```python
@app.get("/skyrocket/")
def skyrocket()
    return ...
```

Note: In FastAPI and Django the first item has precedence.

**Comment by jph00** [comment]
FastHTML doesn't do anything that changes Starlette's handling here AFAIK -- we just do self.routes.add. In Starlette the routes are just looked at in order from top to bottom. Are you seeing something different in FastHTML? If so, can you show me a short example of the behavior?

**Comment by johnowhitaker** [comment]
I don't see a collision if you put the 'skyrocket' one first:

```python
from fasthtml import FastHTML

app = FastHTML()

@app.get("/skyrocket/")
def skyrocket():
    return "Skyrocket to the moon!"

@app.get("/{slug}/")
def slug_test(slug: str):
    print(slug)
    return f"Got slug: {slug}"
```

![Screenshot from 2024-06-24 07-44-08](https://github.com/AnswerDotAI/fasthtml/assets/6575163/724f7f45-6aa9-4fe9-99b6-ba50350cbeca)
![Screenshot from 2024-06-24 07-44-03](https://github.com/AnswerDotAI/fasthtml/assets/6575163/9800884c-1927-4046-9fa4-7428d2c062ed)

**Comment by jph00** [comment]
Thanks for testing it Johno!
