### ISSUE TITLE
hx-swap-oob broken in 0.3.0

### ISSUE THREAD

**Issue by nibinho** [AnswerDotAI/fasthtml#239]
Hi,

first of all: Thanks a lot for this framework and the work you are putting in...I´ve been looking at htmx for a while now and have been feeling Streamlit fatique a lot; it has been wonderful and a pleasure to play around with FastHTML so far! 🚀 

That being said, I think the newest release might have broken the `hx-swap-oob` attribute. It gets rendered as `hx-swap:oob` right now. If used with the unpacked dictionary approach `**{"hx-swap-oob": "true"}` it works as expected.
I guess this will probably be an easy fix?! If helpful, here is a small (I hope reproducible) snippet that shows the problem: 

```python

from fasthtml.common import *

app, _ = fast_app()


@app.get("/")
def index():
    return Titled(
        "HX-Swap-Oob Bug?!",
        P("This should get swapped out", id="swap-bug"),
        Button(
            "This does not work as expected",
            hx_get="/buggy",
            hx_target="#output",
            hx_swap="afterend",
        ),
        Button(
            "This does work as expected",
            hx_get="/working",
            hx_target="#output",
            hx_swap="afterend",
        ),
        P(id="output"),
    )


@app.get("/buggy")
def _():
    return P("Text that gets appended"), P(
        "This should be swapped in out of bound", id="swap-bug", hx_swap_oob="true"
    )


@app.get("/working")
def _():
    return P("Text that gets appended"), P(
        "This should be swapped in out of bound",
        id="swap-bug",
        **{"hx-swap-oob": "true"},
    )


serve()
```

**Comment by nibinho** [comment]
Btw this also doesn´t work anymore: `hx_push_url="/some-url"` gets converted into `hx-push:url="/some-url"`.
I´d guess this probably extends to all attributes with more than one underscore in them?!

**Comment by jph00** [comment]
Fixed now - many apologies.

**Comment by nibinho** [comment]
No worries, I think it is kind of crazy how complete and mostly seamlessly extensible the whole thing is already...happy to deal with minor bugs/inconveniences at this stage. Thanks a lot! 😃
