### ISSUE TITLE
Virtualenv problem

### ISSUE THREAD

**Issue by mroberts1** [AnswerDotAI/fasthtml#271]
I am unable to install fasthtml without an activated virtualenv:

```
> pip install python-fasthtml

"ERROR: Could not find an activated virtualenv (required)"
```

The problem appears to be that my pip default setting is to require an activated virtualenv. How do I unset it? I am running MacOS 12.7, with zsh shell.

This is a continual problem whenever I try to install anything Python-related and I am forced to create a virtualenv before I can install anything. I understand why this is, and I was able to install fasthtml after creating a fasthtml virtualenv. It's just that I don't always want to have to use a virtualenv and being forced to do so every time is inconvenient.

**Comment by ggop** [comment]
Try `export PIP_REQUIRE_VIRTUALENV=false`.
Source: https://stackoverflow.com/a/16460480

**Comment by mroberts1** [comment]
> Try `export PIP_REQUIRE_VIRTUALENV=false`. Source: https://stackoverflow.com/a/16460480

Many thanks!
