### ISSUE TITLE
Any Consideration for SEO

### ISSUE THREAD

**Issue by seun-otosho** [AnswerDotAI/fasthtml#275]
Hi Great Team,

What a great work is going on here. .. tried it and it is super to be able to create a whole application without having to touch HTML, CSS and javascript.

Just one of my thoughts though for now. .. if one is going to use this to build a blog or a content web application . .. how would one handle SEO, and search engine crawling?

**Comment by jph00** [comment]
There's no special features for SEO -- you'd need to ensure the main routes you wanted crawled are accessible from your home page directly.
