### ISSUE TITLE
Unconventional Python formatting is off-putting: why not use ruff?

### ISSUE THREAD

**Issue by corneliusroemer** [AnswerDotAI/fasthtml#277]
I love the idea of fasthtml and am very keen to try it out. 

I wanted to share some honest feedback of some first impressions that bugged me: the unusual way Python code (examples and source) is formatted. It's neither pep8 nor black. It really increases the mental load of reading the code (at least for me, but I'm sure it'll be similar for others).

I get that you might want to minimize lines of code in examples, but even there, I'd argue that using standard formatting is worth saving the few extra lines.

In particular for examples I would expect very standard formatting - what you do with source code is less important as it will be read by far fewer people. But example formatting is of utmost importance.

Has the lack of use of a formatter (e.g. ruff) for examples been a conscious decision?

Some of the code formatting changes are just hard to comprehend. Why is t here no whitespace after `app` in `app,rt` in the `main.py` in the README.md?

<img width="1284" alt="image" src="https://github.com/user-attachments/assets/9fc186da-197b-4ab6-8357-2949682568db">

This is much more readable IMHO:

```py
app, rt = fast_app()

@rt("/")
def get():
    return Div(P("Hello World!"), hx_get="/change")
```

I find this much harder to parse than the formatted version:

https://github.com/AnswerDotAI/fasthtml/blob/16711bb311ae1f1eae2fb884e4aa5f6a4942f085/demo/main.py#L15-L16

Formatted (with ruff):

```
    new_frm = Form(
        Group(Input(name="title", placeholder="Title"), Button("Add")),
        hx_post="/",
        target_id="todo-list",
        hx_swap="beforeend",
    )
```

I wouldn't know at first glance whether `hx_post` are arguments for `Form` or `Group`.

Some of the source code lines are so long that one can't even scroll all the way to the end of the line in Github's code viewer:
<img width="1774" alt="Brave Browser 2024-08-13 16 17 17" src="https://github.com/user-attachments/assets/6a483171-2d7f-4c94-9078-32be6ed1e20e">
https://github.com/AnswerDotAI/fasthtml/blob/main/fasthtml/svg.py

I checked for duplicates but couldn't find any.

**Comment by ncoop57** [comment]
Hey @corneliusroemer thanks for the discussion. I think this post from the fast.ai encapsulates are position on coding style when it comes to this lib and most of the other ones here at answer: https://docs.fast.ai/dev/style.html

**Comment by pydanny** [comment]
Hey @corneliusroemer, thanks for your contributions thus far. I too come from a ruff/pep8 background and it took me a bit to get the hang of the fastai coding style. What I discovered was that it increased my productivity and helped with developing a more functional programming style within Python.

That said, you are correct about the `svg.py` module being a bit long. There are absolutely allowances in the fastfi coding style to break up overly long function names. Since we do it manually, sometimes we haven't gotten to everything yet. That module is one of them. 😉

**Comment by corneliusroemer** [comment]
@jph00 @pydanny gentle suggestion to close as "not planned"

**Comment by jph00** [comment]
It's also true that `demo` example is horribly formatted -- it's pretty old and we've found much better ways more recently. Will shortly commit a version which shows this way:
```python
async def get(request):
    new_frm = Form(hx_post='/', target_id='todo-list', hx_swap='beforeend')(
        Group(
            Input(name='title', placeholder='Title'),
            Button('Add')
        )
    )
    items = Ul(*todos(), id='todo-list')
    logout = A('logout', href=basic_logout(request))
    return Titled('Todo list', new_frm, items, logout)
```
