### ISSUE TITLE
How to specify `hx-on:click` etc?

### ISSUE THREAD

**Issue by corneliusroemer** [AnswerDotAI/fasthtml#283]
I'm trying to figure out how to do something like `<div hx-on:click="alert('Clicked!')">Click</div>` with fasthtml.

Is this possible? There seems to be only an `hx-on` attribute, but here we actually want something like `hx-on:click` as the attribute which isn't a legal python argument name.

See https://htmx.org/attributes/hx-on/

**Comment by pydanny** [comment]
Hey @corneliusroemer 👋🏻 

This [doc on FT Component attributes](https://docs.fastht.ml/explains/explaining_xt_components.html#attributes) should provide the answer. 😄 If not, ping me by name and I'll reopen this ticket.

**Comment by corneliusroemer** [comment]
It does indeed, thanks @pydanny!

For those who don't want to go to the docs and find the answer, here it is:

```py
Div(**{"hx-on:click": "alert('Hello World!')"})
```
