### ISSUE TITLE
Game of Life example doesn't work with latest fasthtml

### ISSUE THREAD

**Issue by corneliusroemer** [AnswerDotAI/fasthtml#289]
I was trying to get the Game of Life example to work with the latest fasthtml but I couldn't.

I was getting 400 errors. It turns out that `hx-vals` seem to be messed up. 

As the code hasn't changed in 4 weeks, it must have been a breaking change in fasthtml?

Relevant line: 

https://github.com/AnswerDotAI/fasthtml-example/blob/bdd4cc2257cf3c641e158ab23e83ab090d7c090a/00_game_of_life/main.py#L47

This is the html as produced by the working example (probably using old fasthtml): 
<img width="1827" alt="Brave Browser 2024-08-14 02 00 11" src="https://github.com/user-attachments/assets/b1e3789f-380f-41b4-ae04-a19db067c0b7">

This is using latest example and fasthtml locally:
<img width="1291" alt="Brave Browser 2024-08-14 02 00 44" src="https://github.com/user-attachments/assets/4983c75d-f8d3-4442-8380-51afb89abee3">

Note that `hx-vals` arg is not valid JSON anymore! If I substitute  `hx_vals=json.dumps({'x': x, 'y': y})` then things work again.

So 2 options:
- A) This was an intentional breaking change. Then example needs to change
- B) This is unintentional, a bug.

**Comment by jph00** [comment]
@ncoop57 any chance you could take a look?

**Comment by corneliusroemer** [comment]
This was fixed with #288 - just confirmed with v0.3.6! Thanks @jph00.
