### ISSUE TITLE
Add more precise typing to make development easier

### ISSUE THREAD

**Issue by corneliusroemer** [AnswerDotAI/fasthtml#292]
It would really help discoverability if there was better type hinting of common functions/classes.

For example `fast_app` seems to sometimes return some database tables, but this VS Code's Pylance has no clue about that due to fast_app returning `Any`

**Comment by jph00** [comment]
Quite a bit of the library is fairly dynamic so there aren't always more precise types available. FastHTML isn't really designed to work with Pylance - I'd recommend turning it off for FastHTML projects.

**Comment by jph00** [comment]
(Having said that, if you want to do a PR for places where you're 100% sure you know the type that is always returned, feel free to add them.)

**Comment by corneliusroemer** [comment]
Thanks! Pylance doesn't cause any issues, it's just that I'm used to it helping me figure out how to use a new framework/package - and in this case it's notably useless.

I'll try to make PRs when I find easy wins.
