### ISSUE TITLE
Recommended pre-commit command ` nbdev_export && nbdev_clean && nbdev_trust` changes things for me

### ISSUE THREAD

**Issue by corneliusroemer** [AnswerDotAI/fasthtml#301]
Per contributing.md I'm supposed to run `nbdev_export && nbdev_clean && nbdev_trust` before each commit.

However, if I do so on current main, I get a huge diff. So either:
a) people haven't run that command in a long time or
b) different versions of the hooks/jupyter/etc. have discrepant output

In case of a), one should maybe add pre-commit hooks and check them in CI for PRs. This might be useful anyways to simplify onboarding.

In case of b), one should pin versions of these tools for development so everyone gets consistent output.

This commit shows what I get when running the command above:

https://github.com/corneliusroemer/fasthtml/commit/8d9ca928a33271d402908ad0eda8089a223f9871#diff-c42647c9ae23bb99e2ee81453fd26419be8d6b570cf17f976b4dfc68b46ffa53\

<img width="2513" alt="image" src="https://github.com/user-attachments/assets/4578f74d-6ed6-4d5a-809f-8f9c385cc2df">

**Comment by jph00** [comment]
Looks like you've got an old version of nbdev. If you keep that up to date you should be consistent -- it's checked in CI.

**Comment by corneliusroemer** [comment]
@jph00 gentle suggestion to close as "not planned"

**Comment by corneliusroemer** [comment]
I'm looking into this now again.

I realized I installed an old version of nbdev because I used conda-forge, see https://github.com/conda-forge/nbdev-feedstock/issues/5

However, even after installing directly from pip, I still get differences. I install `nbdev` and `jupyterlab` is that correct?

**Comment by jph00** [comment]
Thanks for the update!
