### ISSUE TITLE
katex.js file not included in latest release

### ISSUE THREAD

**Issue by rian-dolphin** [AnswerDotAI/fasthtml#302]
I am encountering an error in the latest version of fasthtml when adding `KatexMarkdownJS()` to the headers of an app.  This worked in previous versions. 

The issue is that the file `katex.js` is referenced by code in the latest release, see [here](https://github.com/AnswerDotAI/fasthtml/blob/2bfb164ce4c5aef16773bb50527c7a54b221830d/fasthtml/js.py#L49), however there is no `katex.js` file (or any .js files) are downloaded when pip installing the latest version. This might be related to a recent migration of the js.py module into a notebook so it documents nicely but I am unsure on that pipeline!

Minimum app to reproduce:
```python
from fasthtml.common import *
hdrs = KatexMarkdownJS()
app, rt = fast_app(hdrs=hdrs)
@app.get("/")
def page():
    return Div("Hello, world!")
serve()
```

Traceback:
```
Traceback (most recent call last):
  File "/Users/***/Documents/my_repo/minimum.py", line 3, in <module>
    hdrs = KatexMarkdownJS()
           ^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/fasthtml/js.py", line 50, in KatexMarkdownJS
    scr = ScriptX(fn, display_delim=re.escape(display_delim), inline_delim=re.escape(inline_delim),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/fasthtml/xtend.py", line 155, in ScriptX
    s = loose_format(Path(fname).read_text(), **kw)
```

**Comment by jph00** [comment]
Many thanks - should be fixed in the latest release.
