### ISSUE TITLE
image webpage to railway

### ISSUE THREAD

**Issue by sky1ove** [AnswerDotAI/fasthtml#313]
Hi, Thanks for making this great library! I love it. I don't know if it's appropriate to put this question here, if not, please close it.

I'm making a gallery image web using fastHTML, and deploy it using railway.

I put all of the images in the /data folder, but whenever I do "railway up -c" or "fh_railway_deploy <project name>", it always shows "failed upload, too large"

Do you know any solutions for big image data? Thanks!

**Comment by pydanny** [comment]
You can host large files on another server. S3, Cloudflare, or something like that. 

Another place to look for assistance is in the railway help and discussion boards: https://help.railway.app/

Good luck!
