### ISSUE TITLE
[BUG] Cannot access attribute "get" for class "FastHTML"

### ISSUE THREAD

**Issue by mohd-saaduddin-ansari** [AnswerDotAI/fasthtml#319]
**Important Notice**
We do not provide support through GitHub issues. For community-based help, please use either:
- GitHub Discussions tab
- Our [Discord channel](https://discord.gg/qcXvcxMhdP)

If you're reporting a bug, please continue with this template.

**Describe the bug**

**Minimal Reproducible Example**
Provide a minimal code snippet that reproduces the issue. This is crucial for us to understand and fix the bug quickly.

```python
from fasthtml import FastHTML

app = FastHTML()

@app.get("/")
def home():
    return "<h1>Hello, World</h1>"
```

**Expected behavior**
The app is supposed to run with out errors but am getting unsuported attribute error

**Environment Information**
Please provide the following version information:
- fastlite version:
- fastcore version:
- fasthtml version: python-fasthtml = "^0.4.3"

**Confirmation**
Please confirm the following:
- [x] I have read the FAQ (https://docs.fastht.ml/explains/faq.html)
- [x] I have provided a minimal reproducible example
- [x] I have included the versions of fastlite, fastcore, and fasthtml
- [x] I understand that this is a volunteer open source project with no commercial support.

**Additional context**

**Screenshots**

<img width="1390" alt="image" src="https://github.com/user-attachments/assets/c780b6be-6e3a-42b3-b783-1353b2641d76">

**Comment by Viddesh1** [comment]
Hello @mohd-saaduddin-ansari ,

The blow python code along with command is working fine on ```python-fasthtml 0.4.4 version``` in my local machine.

```python
from fasthtml import FastHTML

app = FastHTML()

@app.get("/")
def home():
    return "<h1>Hello, World test</h1>"
```
```bash
uvicorn main17:app --reload
```

```
INFO:     Uvicorn running on http://0.0.0.0:5001 (Press CTRL+C to quit)
INFO:     Started reloader process [72047] using WatchFiles
INFO:     Started server process [72066]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:59864 - "GET / HTTP/1.1" 200 OK
```

```python
# from fasthtml import FastHTML
from fasthtml.common import *

app = FastHTML()

@app.get("/")
def home():
    return "<h1>Hello, World Viddesh</h1>"

serve()
```
```bash
python3 main17.py
```

```
INFO:     Uvicorn running on http://0.0.0.0:5001 (Press CTRL+C to quit)
INFO:     Started reloader process [72047] using WatchFiles
INFO:     Started server process [72066]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:59864 - "GET / HTTP/1.1" 200 OK
```

![hello_test](https://github.com/user-attachments/assets/88e18edf-733e-47f4-b20b-926d7a7f2fec)


Best Regards!
Viddesh

**Comment by tekumara** [comment]
Also seeing this. Whilst the code works when run, pyright/pylance errors because these methods are dynamically added to the FastHTML class, see here: https://github.com/AnswerDotAI/fasthtml/blob/db40c7df055d0e468557e7fc983b5965941929c9/fasthtml/core.py#L477

So for these methods to be seen by the type checker, I think some type stubs would be needed.
