### ISSUE TITLE
Question:Fasthtml & Htmx

### ISSUE THREAD

**Issue by j209** [AnswerDotAI/fasthtml#325]
I apologize for bringing this matter up here.
Does Fasthtml using htmx under the hood?
I asked the AI ​​this question and this is how it answered:
"In essence, FastHTML is a layer on top of HTMX that makes it easier to build web applications with Python by providing a more Pythonic way to interact with HTMX."

**Comment by pydanny** [comment]
Yes, FastHTML leverages HTMX. You could say that it is "under the hood".

It's explained in depth here: https://about.fastht.ml/tech
