### ISSUE TITLE
[BUG] Object of type "FT" is not callable (pyright/pylance)

### ISSUE THREAD

**Issue by tekumara** [AnswerDotAI/fasthtml#329]
**Describe the bug**

pyright/pylance errors with:
```
error: Object of type "FT" is not callable
    Attribute "__call__" is unknown (reportCallIssue)
```

**Minimal Reproducible Example**

```python
from fasthtml.common import Form,Div

Form()(Div())
```

**Expected behavior**

No pyright/pylance error.

**Environment Information**

- fastlite version: fastlite==0.0.9
- fastcore version: fastcore==1.7.1
- fasthtml version: python-fasthtml==0.4.3

**Confirmation**
Please confirm the following:
- [x] I have read the FAQ (https://docs.fastht.ml/explains/faq.html)
- [x] I have provided a minimal reproducible example
- [x] I have included the versions of fastlite, fastcore, and fasthtml
- [x] I understand that this is a volunteer open source project with no commercial support.

**Screenshots**

vscode screenshot:

![CleanShot 2024-08-18 at 20 19 29@2x](https://github.com/user-attachments/assets/7059a040-4a10-4f7a-8724-c79f9c9130de)

**Comment by jph00** [comment]
FastHTML isn't compatible with pylance.
