### ISSUE TITLE
In the "Web Devs Quickstart" page, imports are not uniform

### ISSUE THREAD

**Issue by omennemo** [AnswerDotAI/fasthtml#330]
In the "Web Devs Quickstart" Routing section the import made is from fasthtml.fastapp which does not include 'Titled', 'P' & 'serve' functions. Resulting in below error.

<img width="1416" alt="Screenshot 2024-08-18 at 5 00 18 PM" src="https://github.com/user-attachments/assets/9ebd0126-d1ef-4801-b528-d1b5a8a50560">

**Comment by jph00** [comment]
I think we fixed that a while ago. Let me know if you find a page that still has it.
