### ISSUE TITLE
[BUG] ext:static in route doesn't work

### ISSUE THREAD

**Issue by samueller** [AnswerDotAI/fasthtml#348]
Docs show the following code for [changing static media file locations](https://docs.fastht.ml/tutorials/quickstart_for_web_devs.html#other-static-media-file-locations):
```python
@rt("/{fname:path}.{ext:static}")
async def get(fname:str, ext:str): 
    return FileResponse(f'public/{fname}.{ext}')
```

I added that route and put my static content in `public/`, but I only got `Not Found`s. When I remove `:static` from the route decorator, it worked. Was `:static` a typo? Also, what is `:path`?

**Environment Information**
Please provide the following version information:
- fastlite version: 0.0.9
- fastcore version: 1.7.1
- fasthtml version: 0.4.3

**Confirmation**
Please confirm the following:
- [x] I have read the FAQ (https://docs.fastht.ml/explains/faq.html)
- [x] I have provided a minimal reproducible example
- [x] I have included the versions of fastlite, fastcore, and fasthtml
- [x] I understand that this is a volunteer open source project with no commercial support.

**Comment by jph00** [comment]
Please use discussions or discord for help.
