### ISSUE TITLE
[BUG] Changing static media file location for .js files doesn't work

### ISSUE THREAD

**Issue by samueller** [AnswerDotAI/fasthtml#349]
In issue #348, I mentioned how `:static` causes changing static media file locations to not work:
```python
@rt("/{fname:path}.{ext:static}")
async def get(fname:str, ext:str): 
    return FileResponse(f'public/{fname}.{ext}')
```
The fix is to simply remove `:static`. Then my static files are served. However, Javascript (`*.js`) files are still only served from the root directory. The above `get` function is never called. I assume this is also the case for the standard static files like HTML and images.

**Environment Information**
Please provide the following version information:
- fastlite version: 0.0.9
- fastcore version: 1.7.1
- fasthtml version: 0.4.3

**Confirmation**
Please confirm the following:
- [x] I have read the FAQ (https://docs.fastht.ml/explains/faq.html)
- [x] I have provided a minimal reproducible example
- [x] I have included the versions of fastlite, fastcore, and fasthtml
- [x] I understand that this is a volunteer open source project with no commercial support.

**Comment by jph00** [comment]
Please use discussions or discord for help.
