### ISSUE TITLE
[BUG] Mouseover example points to a CDN resource that fails due to SSL error

### ISSUE THREAD

**Issue by muraii** [AnswerDotAI/fasthtml#353]
**Describe the bug**
The example on the homepage of FastHTML is a mouseover effect of a card with a fantasy image rendered on it. The image doesn't show up anymore.

**Minimal Reproducible Example**
Visit https://fastht.ml and scroll down.

**Expected behavior**
The image renders on the HTML card.

**Notes**
The issue is on [this line](https://github.com/AnswerDotAI/fasthtml-example/blob/0f9a5791a9d24a4bb9e47945082db5f65ca823a9/3d-component/main.py#L17) in the `fasthtml-example/3d-component/main.py` file. The error I receive when trying to look at that image resource is

>Secure Connection Failed
>
>An error occurred during a connection to ucarecdn.com. Cannot communicate securely with peer: no common encryption algorithm(s).
>
>Error code: SSL_ERROR_NO_CYPHER_OVERLAP

**Comment by jph00** [comment]
Works for me -- requires https though.
