### ISSUE TITLE
[BUG] Img embedding not working

### ISSUE THREAD

**Issue by Incblob** [AnswerDotAI/fasthtml#388]
Description:
Img does not work. I have a test.jpg in the root folder of my project. 
Passing this path to an Img object does not display the image. I'm getting the 'image-not-found' icon. 
This is how the images are displayed in the Img Generator tutorial. 

Here is the python code:
```@app.get("/")
def home():
    return Main(Img(src="test.jpg"))
```

I get a 404 Not found error in the logs. (ignore the strange formatting, dunno why that is)
`INFO:     127.0.0.1:56914 - GET /test.jpg HTTP/1.1 404 Not Found`

The html in the inspector is the following: 
`<img src="test.jpg">`

It seems to be correct, but the image is clearly not being fetched. 
I've tried variations such as `/test.jpg` or `...localhost:5002/test.jpg` but nothing works. 
I've tried clearing the browser cache, no changes there either. 

**Expected behavior**
An image should appear.

**Environment Information**
Please provide the following version information:
- fastlite version: 0.0.10
- fastcore version: 1.7.2
- fasthtml version: 0.5.0

![image](https://github.com/user-attachments/assets/e5e0cc6c-ea8f-4417-aae9-2b1260a7126c)

**Comment by pydanny** [comment]
Try it with a leading slash `/`:

```python
def home():
    return Main(Img(src="/test.jpg"))
```

Let me know if that resolves your issue. If not, I'll reopen the ticket.

**Comment by pydanny** [comment]
> > Try it with a leading slash `/`:
> > 
> > ```python
> > def home():
> >     return Main(Img(src="/test.jpg"))
> > ```
> > 
> > Let me know if that resolves your issue. If not, I'll reopen the ticket.
> 
> Hi, thanks for the quick reply. 
> As I mentioned, I've tried all the variations of the path, including "/test.jpg" and even the absolute path. 
> Neither worked. 
> 
> @pydanny 

Do you have a repo or a minimal code example I can try?

**Comment by Incblob** [comment]
@pydanny 
https://github.com/Incblob/fastHTML_minimal_bug
Here is a minimal repo, Or you can just use the code directly.

**Comment by johnowhitaker** [comment]
You need a static route to serve files (like the image file) - either use fast_app (which adds this automatically) or add a route like:
```python
@rt("/{fname:path}.{ext:static}")
def get(fname:str, ext:str): return FileResponse(f'{fname}.{ext}')
```

**Comment by Incblob** [comment]
@pydanny thank you for your help
@johnowhitaker Thanks, that works. 
However `@rt` is used with the fast_app, which wouldn't need the explicit route declaration.
Here's the variant for FastHTML for anyone looking:
```
@app.get("/{fname:path}.{ext:static}")
def get(fname: str, ext: str):
    return FileResponse(f"{fname}.{ext}")
```
This is not documented, should I open an issue for the documentation, or is that unnecessary?
