### ISSUE TITLE
async script tag not handled properly due to special key word

### ISSUE THREAD

**Issue by ncoop57** [AnswerDotAI/fasthtml#39]
The script tag can have the [async keyword](https://www.w3schools.com/tags/att_script_async.asp) (e.g., `<script async id="search-script" src="../assets/js/search.js"></script>`, which is not currently handled by fasthtml nor the html2xt function since async is a special keyword in python causing a syntax error:

```
Script(async='', id='search-script', src='../assets/js/search.js')
           ^
SyntaxError: invalid syntax
```

I think we will need to specify a synonym for what we will use `async` for in python. Perhaps we could use capital `Async`? `Script(Async='', id='search-script', src='../assets/js/search.js')`

**Comment by jph00** [comment]
If you pop an `_` before the attr, it'll be removed automatically. So use `_async`. (PS: please at-mention me on issues/PRs so I don't miss them!)
