### ISSUE TITLE
[FEATURE] Usage with pyxl

### ISSUE THREAD

**Issue by notpushkin** [AnswerDotAI/fasthtml#395]
**Is your feature request related to a problem? Please describe.**
Not really! But I do think a JSX-like syntax would be nice.

**Describe the solution you'd like**
Basically, integrate with pyxl4: https://github.com/pyxl4/pyxl4

**Example code**
Provide an example of how you imagine the feature working:

```python
# coding: pyxl
from fasthtml_pyxl import *

page = <html>
    <head><title>Some page</title></head>
    <body>
        <div>
            Some text,
            <a href='https://example.com'>a link</a>,
            <img src="https://placehold.co/200" class='myclass' alt="an image" />
        </div>
    </body>
</html>

print(to_xml(page))
```

**Similar implementations**
None I can think of! (Except for the pyxl4 itself, and older versions of course)

**Problem solved**
N/A

**Additional context**
N/A

**Confirmation**
Please confirm the following:
- [x] I have checked the existing issues and pull requests to ensure this feature hasn't been requested before.
- [x] I have read the project's documentation to ensure this feature doesn't already exist.

**Comment by jph00** [comment]
That project is long dead, and I don't like all that extra typing myself - but you could make this an external project if you wanted; no need to put it in fasthtml itself afaict.
