### ISSUE TITLE
[FEATURE] Automatically create .gitignore file for FastHTML projects

### ISSUE THREAD

**Issue by comhar** [AnswerDotAI/fasthtml#397]
**Is your feature request related to a problem? Please describe.**
Currently when starting a new FastHTML project, I create an empty .gitignore file, search for a Python .gitignore template, copy the contents, and populate my local .gitignore.

**Describe the solution you'd like**
I would like to add a command line tool `fh_init` to automate this process. See draft [PR](https://github.com/AnswerDotAI/fasthtml/pull/398)

**Example code**
See draft [PR](https://github.com/AnswerDotAI/fasthtml/pull/398)

**Similar implementations**
None

**Problem solved**
This is a minor quality of life issue that saves a little time + effort. It also partially mitigates the risk of accidentally pushing secrets, a sqlite db, or other files to remote. 

**Additional context**
None

**Confirmation**
Please confirm the following:
- [x] I have checked the existing issues and pull requests to ensure this feature hasn't been requested before.
- [x] I have read the project's documentation to ensure this feature doesn't already exist.

**Comment by jph00** [comment]
Not sure about this - doesn't really seem fasthtml specific? And nbdev gives you a .gitignore if you want one. Maybe better to create a little github template repo with a basic main.py skeleton, requirements.txt, and .gitignore?

**Comment by comhar** [comment]
> Not sure about this - doesn't really seem fasthtml specific? And nbdev gives you a .gitignore if you want one. Maybe better to create a little github template repo with a basic main.py skeleton, requirements.txt, and .gitignore?

True, this is a minor inconvenience on non-fasthtml projects as well.

Setting up a template repo is a simpler approach and probably easier to extend over time when other best practices emerge. Closing this PR.
