### ISSUE TITLE
why not to use Notebook as a development environment?

### ISSUE THREAD

**Issue by zverianskii** [AnswerDotAI/fasthtml#40]
Hello,

First of all, thank you very much for the new library. I really appreciate the effort to lower the barrier in web development.

When I assist DS/ML professionals in understanding how to use web frameworks, I find it most helpful when they can experiment within a notebook environment. This is what I anticipated from the FastHTML examples, given Jeremy's previous tools.

From my experience, the only issue is the need to redefine routers each time due to how Starlette handles them, but this can be addressed with the following code example as a decorator for routers (probably can be added to app.route in fasthtml):

```python
def hot_realod(func):
    idx_to_del = [
        i for i, r in enumerate(app.routes) if func.__name__ == getattr(r, "name", id)
    ]
    for i, idx in enumerate(idx_to_del):
        del app.routes[idx - i]

    @wraps(func)
    async def inner_func(*args, **kwargs):
        return await func(*args, **kwargs)

    return inner_func
```

Here is an example: we start the app, create a router, change it (to simulate a cell re-run) and then export everything with nbdev (to run with uvicorn in prod)

![image](https://github.com/AnswerDotAI/fasthtml/assets/1670306/b07b05b2-846b-46bf-8a1a-db12486b2c55)

Could you please explain why you chose not to develop in Jupyter?

**Comment by jph00** [comment]
I don't understand why you asked "why you chose not to develop in Jupyter?" We do often develop in Jupyter, and some of the examples in the fasthtml-examples repo include notebooks.

**Comment by zverianskii** [comment]
Let me clarify: Based on your previous work, I expected everything to be entirely in notebooks. However, in the documents I see:

```
For a minimal app, create a file “main.py” as follows:
```

```
Normally you’d save this into a file such as main.py, and then run it in uvicorn using:
```


```
To run this app, place it in a file, say app.py, and then run it with uvicorn app:app --reload
```

So, my question is: did you encounter any issues with notebooks that led you to switch to a more traditional development approach? If not, just disregard this question. Thanks a lot!

**Comment by jph00** [comment]
Got it, thanks for explaining. tbh I don't feel like I've found the perfect way to develop fasthtml apps yet. I'd like to do it all in notebooks, but I'm still switching back and forth a bit atm.

I strongly suspect it's possible to do it all client-side using starlette's TestClient and some js server mocking, like the htmx 'demo' functionality does. That would be the ideal solution, but I'm not sure how to tackle it.

**Comment by jph00** [comment]
(Having said all that, either way the docs will likely focus on non-jupyter dev workflows, since that's what most people are familiar with)

**Comment by zverianskii** [comment]
Thanks for the Answer!
