### ISSUE TITLE
[FEATURE] Add reload on CSS and JS file changes

### ISSUE THREAD

**Issue by pydanny** [AnswerDotAI/fasthtml#401]
**Is your feature request related to a problem? Please describe.**

I would be nice if FastHTMLLiveReload supported CSS and JS files. See https://discord.com/channels/689892369998676007/1247700012952191049/1281138518382350422

**Describe the solution you'd like**

Implement this `uvicorn main:app --reload-include="*.css" --reload-include="*.js"` but in the live_reload.py module and callable from `fast_app()`

**Example code**
Provide an example of how you imagine the feature working:

```python
app, rt = fast_app(reload_css=True, reload_js=True)
```

**Problem solved**

Makes it easier to work with CSS and JS files. There might still be issues with browser caching.

**Confirmation**

Please confirm the following:
- [x] I have checked the existing issues and pull requests to ensure this feature hasn't been requested before.
- [x] I have read the project's documentation to ensure this feature doesn't already exist.

**Comment by RensDimmendaal** [comment]
This may help you @pydanny

Instead of running `serve()` run `serve(reload_includes=["static/*"])`

This solved the issue for me as now the app would reload if I'd change some files in my `static` folder.

**Comment by pydanny** [comment]
Thanks!

In a total facepalm moment I have to admit I added that feature to FastHTML #291 😅
