### ISSUE TITLE
[BUG] please add demo for multi py file ,manage route,like index.py  login.py  user.py

### ISSUE THREAD

**Issue by wjsw1781** [AnswerDotAI/fasthtml#406]
![image](https://github.com/user-attachments/assets/253c5afd-991b-43e5-b284-3639f5b6ac36)

![image](https://github.com/user-attachments/assets/0ebea76a-1c88-40ee-96f8-bb9759217f61)

![image](https://github.com/user-attachments/assets/61b26648-d1a7-4715-8479-04b414fdd58e)

i try to manage many routes in many pyfile ,but  only the first route works? why?

could you give my the right demo?

**Comment by jph00** [comment]
dupe
