### ISSUE TITLE
[BUG] function name goes as a method parameter to router

### ISSUE THREAD

**Issue by zverianskii** [AnswerDotAI/fasthtml#41]
I think this is a bug, starlette router typically expects http method names not a function name:
![image](https://github.com/AnswerDotAI/fasthtml/assets/1670306/1ac6bd34-96e4-449a-9002-068d047520a6)

if you confirm I can look into it, looks like a problem in this if https://github.com/AnswerDotAI/fasthtml/blob/main/fasthtml/core.py#L362

**Comment by jph00** [comment]
Not a bug, a feature -- see the docs.
