### ISSUE TITLE
Handle automatic `datetime.date` form field conversion

### ISSUE THREAD

**Issue by tilman151** [AnswerDotAI/fasthtml#415]
**Describe the bug**
I created a form with an input of type `date` and a corresponding dataclass that contains a `datetime.date` field.
When submitting the form via POST, FastHTML produces a 500 because it cannot convert the ISO format date into a `datetime.date` object.
The function `core._fix_anno` erroneously assumes that conversion is done with the `datetime.date` constructor, but it should be `datetime.date.fromisoformat`. 

```
TypeError: descriptor 'date' for 'datetime.datetime' objects doesn't apply to a 'str' object
```

**Minimal Reproducible Example**

```python
from dataclasses import dataclass
from datetime import datetime

from fasthtml import ft
from fasthtml.common import fast_app, serve

app, rt = fast_app()

@dataclass
class ClsWithDate:
    start_date: datetime.date

@rt("/")
def get():
    return ft.Form(
        ft.Input(name="start_date", type="date"),
        ft.Button("Submit", type="submit", hx_post="/", hx_swap="outerHTML"),
    )

@rt("/")
def post(x: ClsWithDate):
    return ft.P(x.start_date)

serve()
```

**Expected behavior**
The ISO string should be parsed correctly into a `datetime.date` object.

**Environment Information**
Please provide the following version information:
- fastlite version: 0.0.10
- fastcore version: 1.7.5
- fasthtml version: 0.5.2

**Confirmation**
Please confirm the following:
- [x] I have read the FAQ (https://docs.fastht.ml/explains/faq.html)
- [x] I have provided a minimal reproducible example
- [x] I have included the versions of fastlite, fastcore, and fasthtml
- [x] I understand that this is a volunteer open source project with no commercial support.

**Comment by jph00** [comment]
That's a bit of a stretch to call that a "bug". But I do agree that this would be a nice feature to add, so I will add it.

**Comment by FIGBERT** [comment]
At the moment this is limited to the `datetime.date` type—but the [`datetime-local` input type](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/datetime-local) would require a conversion to `datetime.datetime`. The same applies to [`time`](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/time) and `datetime.time`. What is the project stance on adding these automatic conversions?
