### ISSUE TITLE
[BUG] Cannot scroll on swap with server-sent events 

### ISSUE THREAD

**Issue by thinker007** [AnswerDotAI/fasthtml#416]
**Important Notice**

using  sse chat example can not scroll on  sse message

**Comment by jph00** [comment]
Did you try `sse_rand_scroll.py`? That one works for me. If it doesn't, create a new issue in which you fill out the form properly so we can actually help.

**Comment by thinker007** [comment]
> sse_rand_scroll.py

thanks I am going to try

**Comment by thinker007** [comment]
tried sse_rand_scroll.py and not working

the problem is you have to render markdown code then sse_rand_scroll is not working
