### ISSUE TITLE
404 Not Found error when trying to access the routes.

### ISSUE THREAD

**Issue by carlosgonzagacp** [AnswerDotAI/fasthtml#420]
Hi,

I’m currently working on a project using FastHtml and I’m having trouble creating external routes. I have followed the documentation, but I keep encountering a 404 Not Found error when trying to access the routes.

Here is a brief overview of my setup:

app.py:
from fasthtml.common import fast_app, serve
from dotenv import load_dotenv
from routes import register_all_routes

load_dotenv()

app, _ = fast_app()

register_all_routes(app)

print("Registered routes:", app.routes)

serve()

# src/app/routes/__init__.py

from routes.home import home
from routes.usuarios import users

def register_all_routes(rt):
    rt('/', home)
    rt('/users', users)
    rt('/home', home)

# src/app/routes/home.py

from fasthtml.common import Div, H1, P, A

def home():
    return Div(
        H1('Home Page'),
        P('Welcome to the API. Please select one of the options below:'),
        A('Usuários', href='/users', _class='btn'),
        P(),
      
    )

Despite this setup, I still receive a 404 error when trying to access the routes. Could you please provide guidance on how to properly create and register external routes in FastHtml?

Thank you for your help!

Feel free to adjust the text as needed. If you need any more assistance, let me know!

**Comment by jph00** [comment]
We don't provide support thru issues, sorry.
