### ISSUE TITLE
Is part of your BYO Blog tutorial missing?

### ISSUE THREAD

**Issue by paul-s-johnson** [AnswerDotAI/fasthtml#431]
I appears to me like it got chopped off: https://docs.fastht.ml/tutorials/tutorial_for_web_devs.html

**Comment by jph00** [comment]
I think @pydanny hasn't finished it yet. Danny should we unpublish it until it's done, or do you think it's still worth keeping in this form for now?

**Comment by pydanny** [comment]
Yes, I think we should unpublish it for now.

**Comment by pydanny** [comment]
Closing as the blog tutorial is now unpublished.

**Comment by dvquy13** [comment]
Hi @pydanny do we have a timeline when this BYO Blog tutorial will be published again?
