### ISSUE TITLE
[BUG] Fix Uncaught SyntaxError

### ISSUE THREAD

**Issue by pydanny** [AnswerDotAI/fasthtml#432]
**Describe the bug**

On JS load this error happens:

> Uncaught SyntaxError: The requested module 'https://cdn.jsdelivr.net/gh/answerdotai/fasthtml-js/fasthtml.js' does not provide an export named 'proc_htmx'

Amongst other things, this breaks markdown rendering. See photos at bottom for example.

**Minimal Reproducible Example**

```python
from fasthtml.common import *

app, rt = fast_app(hdrs=[MarkdownJS(), HighlightJS()])

@rt("/")
def home(): return Div("Hello, World")

serve()
```

**Expected behavior**

Calling proc_htmx shouldn't generate errors

**Environment Information**
Please provide the following version information:
- fastlite version: 0.0.11
- fastcore version: 1.7.8
- fasthtml version: 0.6.0

**Confirmation**
Please confirm the following:
- [x] I have read the FAQ (https://docs.fastht.ml/explains/faq.html)
- [x] I have provided a minimal reproducible example
- [x] I have included the versions of fastlite, fastcore, and fasthtml
- [ ] I understand that this is a volunteer open source project with no commercial support.

**Screenshots**

<img width="741" alt="Screenshot 2024-09-16 at 16 55 33" src="https://github.com/user-attachments/assets/953fcbce-9556-4e0c-ba53-720fed807ba8">

<img width="803" alt="Screenshot 2024-09-16 at 16 56 03" src="https://github.com/user-attachments/assets/78ad7e9b-420a-4eac-850a-6460d978dcf8">

**Comment by jph00** [comment]
Fixed by #434
