### ISSUE TITLE
[BUG] Hello World app gives javascript syntax error

### ISSUE THREAD

**Issue by leifmetcalf** [AnswerDotAI/fasthtml#435]
**Describe the bug**
The hello world app from the quickstart gives this error:

> Uncaught SyntaxError: export declarations may only appear at top level of a module fasthtml.js:1:1

No functionality I can tell is affected.

**Minimal Reproducible Example**

```python
from fasthtml.common import *

app, rt = fast_app()

@rt("/")
def get():
    return Titled("FastHTML", P("Let's do this!"))

serve()
```

**Environment Information**
Please provide the following version information:
- fastlite version: 0.0.11
- fastcore version: 1.7.8
- fasthtml version: 0.6.1

**Comment by RNGMonk** [comment]
Hey @leifmetcalf,

I haven't been able to reproduce with the same versions on my Linux machine. Are you still having this problem with the latest version?

**Comment by leifmetcalf** [comment]
I can't reproduce it on fasthtml 0.8.0.
