### ISSUE TITLE
[FEATURE] Improve spacing between elements

### ISSUE THREAD

**Issue by pydanny** [AnswerDotAI/fasthtml#441]
**Is your feature request related to a problem? Please describe.**

FastHTML no longer includes a space between HTML elements. This can cause issues with lists of `A` tags and other elements.

**Describe the solution you'd like**

An concise, easy-to-use method of adding spaces between tags.

**Example code**

Perhaps simply add this to FastHTML or FastCore:

```python
def S(e):
    return Span(e, ' ')
```

Should also consider `*args` and `**kwargs`, the above approach is arguably simplistic.

Another approach would be tor add a `space` or `s` attribute to tags

```python
# Space attribute
A(href='http://fastht.ml', space=True)('FastHTML')

# S shortcut
A(href='http://fastht.ml', S=True)('FastHTML')
```

**Similar implementations**

I used the `S()` function approach in the releases app. You can see the definition of the tag and one of the implementations [here](https://github.com/pydanny/releases/blob/f56a81dce6e673f9c04d0e6b1d92f854d16c38b6/main.py#L42-L46).

**Problem solved**

Makes it easier to format text.

**Confirmation**
Please confirm the following:
- [x] I have checked the existing issues and pull requests to ensure this feature hasn't been requested before.
- [x] I have read the project's documentation to ensure this feature doesn't already exist.

**Comment by dgwyer** [comment]
Interesting suggestion. Do you happen to know which PR it was that reverted the spacing? Curious to know how it was originally implemented.

Also, would you be able to provide any examples of HTML markup where you would find spacing around elements useful that's not working anymore due to the FastHTML update? It might help to figure out alternate solutions.

Also, I just tested the following alternatives. Would any of these be useful?

```
@rt("/")
def get():
    # return Div(A('Link #1'), NotStr('&nbsp;'), A('Link #2'))
    # return Div(A('Link #1'), NotStr(' '), A('Link #2'))
    #return Div(A('Link #1', style="margin-right: 1rem;"), A('Link #2'))
    return Div(A('Link #1'), ' ', A('Link #2'))
```

**Comment by pydanny** [comment]
I'm not sure when things changed and tags stopped having breaking HTML between them, I just noted that the headers and footers of my personal site at https://daniel.feldroy.com lost the spaces between them.

**Comment by pydanny** [comment]
Addressed with `Nbsp()`
