### ISSUE TITLE
[BUG] Can't use with ddtrace

### ISSUE THREAD

**Issue by derekgliwa** [AnswerDotAI/fasthtml#451]
**Important Notice**
We do not provide support through GitHub issues. For community-based help, please use either:
- GitHub Discussions tab
- Our [Discord channel](https://discord.gg/qcXvcxMhdP)

If you're reporting a bug, please continue with this template.

**Describe the bug**
When using in an app with ddtrace, the wrapping code fails due to not using named params in the FastHTML initialization code.

**Minimal Reproducible Example**
(when starting an app with ddtrace):

```
  File "/app.py", line 25, in __init__
    self.fasthtml_app = FastHTML(hdrs=(picolink)) 
                       thtml/core.py", line 536, in __init__
    super().__init__(debug, routes, middleware, excs, on_startup=on_startup, on_shutdown=on_shutdown, lifespan=lifespan)
  File "/.venv/lib/python3.11/site-packages/ddtrace/contrib/internal/starlette/patch.py", line 59, in traced_init
    wrapped(*args, **kwargs)
TypeError: Starlette.__init__() got multiple values for argument 'middleware'
make: *** [start] Error 1
```

**Expected behavior**
Would expect the app to start up properly even when called in an environment attempting to profile with ddtrace (my usecase here is mounting a FastHTML app inside a FastAPI application - so just want to have the app startup without throwing an error).

**Environment Information**
Please provide the following version information:
- fastlite version: 0.0.11
- fastcore version: 1.7.9
- fasthtml version: 0.6.5

**Confirmation**
Please confirm the following:
- [x] I have read the FAQ (https://docs.fastht.ml/explains/faq.html)
- [x] I have provided a minimal reproducible example
- [x] I have included the versions of fastlite, fastcore, and fasthtml
- [x] I understand that this is a volunteer open source project with no commercial support.

**Additional context**
Submitting a PR with proposed fix.

**Screenshots**

**Comment by pydanny** [comment]
@derekgliwa Did your patch resolve the issue? Can we close the ticket?

**Comment by derekgliwa** [comment]
Ah! yes it did - closing
