### ISSUE TITLE
[FEATURE] Add `xtra` keyword argument or function call to MiniDataAPI Spec

### ISSUE THREAD

**Issue by pydanny** [AnswerDotAI/fasthtml#466]
**Is your feature request related to a problem? Please describe.**

The `.xtra` control in the MiniDataAPI spec is powerful, let's explore adding it to the spec.

**Describe the solution you'd like**

- [ ] Document how the implementation should behave
- [ ] Implement in fastlite
- [ ] Document in the MiniDataAPI spec

**Example code**

Here's two ideas

1. As a keyword argument:

```python
todos(xtra={'name': 'Danny'})
```

2. As a chainable function call:

```python
todos(where="status='open'").xtra(name='Danny')
```

**Similar implementations**

Existing .xtra implementation is [here](https://docs.fastht.ml/explains/minidataapi.html#xtra)

**Problems solved**

1. Encourages safer data control practices
2. That `.xtra` is immutable once set makes per-function an improvement to developer UX

**Confirmation**
Please confirm the following:
- [x] I have checked the existing issues and pull requests to ensure this feature hasn't been requested before.
- [x] I have read the project's documentation to ensure this feature doesn't already exist.

**Comment by jph00** [comment]
It should be a keyword argument. Search the fastlite source for anywhere we use `self.xtra` now, and have each of those functions take an `xtra` param. Then, in the function, do `if not xtra: xtra=self.xtra`, and then replace the usage of `self.xtra` in the function with `xtra`. Make sense?

We should implement it and use it first and see if we like it, before we document it.

**Comment by pydanny** [comment]
Closing this because it was resolved months ago.
