### ISSUE TITLE
[FEATURE] Write tool to export the MiniDataAPI tests

### ISSUE THREAD

**Issue by pydanny** [AnswerDotAI/fasthtml#467]
**Is your feature request related to a problem? Please describe.**

It will be easier to write new implementations of the MiniDataAPI spec if there's a way to easily export the tests.

**Describe the solution you'd like**

A CLI tool that simply exports the tests into a new Jupyter notebook with a cell marked for database instantiation. Might also have an export to a Python script for those of us who prefer to work in that medium.

**Example code**
Provide an example of how you imagine the feature working:

```bash
$ fh_export_minidataapi_tests
```

**Similar implementations**

Maybe I'm overthinking this? Maybe we can just provide instructions for copying over the current notebook? Or maybe there's already a way to do it and I just don't know about it?

**Problem solved**

Makes it easier to write MiniDataAPI implementations.

**Confirmation**
Please confirm the following:
- [x] I have checked the existing issues and pull requests to ensure this feature hasn't been requested before.
- [x] I have read the project's documentation to ensure this feature doesn't already exist.

**Comment by jph00** [comment]
Definitely overthinking it Danny! ;)
