### ISSUE TITLE
[BUG] Type changes aren't picked up by MiniDataAPI transforms in fastlite

### ISSUE THREAD

**Issue by pydanny** [AnswerDotAI/fasthtml#477]
**Describe the bug**

Type changes aren't picked up by MiniDataAPI transforms in fastlite

**Minimal Reproducible Example**

Define the table

```python
class User: name: str; pwd: str
users = db.create(User, pk='name')
print(users.schema)
```

Change the table, turning pwd into an `int`:

```python
class User: name: str; pwd: int
users = db.create(User, pk='name', transform=True)
print(users.schema)
```

**Expected behavior**

Types should change upon transform. Status of data after change to a different is something we don't explain.

**Environment Information**
Please provide the following version information:
- fastlite version:
- fastcore version:
- fasthtml version:

**Confirmation**
Please confirm the following:
- [x] I have read the FAQ (https://docs.fastht.ml/explains/faq.html)
- [x] I have provided a minimal reproducible example
- [ ] I have included the versions of fastlite, fastcore, and fasthtml
- [ ] I understand that this is a volunteer open source project with no commercial support.

**Additional context**

**Screenshots**

![image](https://github.com/user-attachments/assets/0d4ef2fa-449b-46fe-a36e-404c78aa0a78)

**Comment by pydanny** [comment]
Not able to reproduce this error:

<img width="817" alt="Screenshot 2024-09-27 at 10 33 36" src="https://github.com/user-attachments/assets/f9a186df-1c46-4416-8755-82901b1b3c24">

I have requested further information from the error reporter.

**Comment by pydanny** [comment]
Closed for now as a non-reproducible error, will reopen if we can reproduce it.

**Comment by hamelsmu** [comment]
I wasn't able to repro it in CI https://github.com/AnswerDotAI/fasthtml/pull/479

**Comment by hamelsmu** [comment]
Nevermind, my test was wrong!
