### ISSUE TITLE
Textarea Component FastHTML

### ISSUE THREAD

**Issue by jgburd79** [AnswerDotAI/fasthtml#532]
How to fill in value for Textarea component?

Let's assume we have a form 

form = Form(
Textarea(id="mytextarea", name="mytextarea", value=Item.text)
)

This does not seam to work in populating a Textarea like you can do for an Input by using the value parameter.

**Comment by timcol** [comment]
Passing the value as a child element might be what you're after.

`Form(Textarea(item.text, id="mytextarea", name="mytextarea"))`

results in a Textarea nested in a Form pre-populated with item.text

**Comment by jgburd79** [comment]
@timcol,
That was exactly it. Simple, but not very intuative. I assumed that I could only use keywords. Nut, it does make sense since the actual test in Textareas in HTML can only be input in between the tags and not as parameters.
