### ISSUE TITLE
[FEATURE] Any example or plan to integrate exist api service 

### ISSUE THREAD

**Issue by thinker007** [AnswerDotAI/fasthtml#536]
If you'd like to discuss your feature idea first with the community (highly recommended!) please visit our [Discord channel](https://discord.gg/qcXvcxMhdP).

bring api to website
not database。

using api build fasthtml website

**Comment by muhis** [comment]
I fail to see why you can't achieve this with python code.

```
from fasthtml.common import *
import requests

app,rt = fast_app()

@rt('/')
def get():
response = requests.get("https://api.sampleapis.com/coffee/hot").  # << Make request
return Div(P(f'Hello World! {response.content}'), hx_get="/change")  # << Use API  response in user response

serve()
```
