### ISSUE TITLE
[BUG] TypeError for tables with not_null and defaults parameters

### ISSUE THREAD

**Issue by Artem-Ter** [AnswerDotAI/fasthtml#542]
**Describe the bug**
Creating a table in database using not_null = set(...) and/or defaults=dict(...) parameters you get TypeError: unhashable type: 'set' or 'dict' accordingly

**Minimal Reproducible Example**

```python
import fasthml.common as fh

db = fh.database('test.db')

users = db.t.users

users.drop()
users.create(
            {
                "id":int,
                "name":str,
                "email":str,
                "pwd":str,
                "phone":str,
                "organization":str,
                "role":int
            },
            pk='id',
            not_null={'email'},
            defaults={'role': 1},
        )
```

**Expected behavior**
Create table with defaults and not null constraints

**Environment Information**
- fastlite version: "0.0.11"
- fastcore version: "1.7.14"
- fasthtml version: "0.6.10"

**Confirmation**
Please confirm the following:
- [x] I have read the FAQ (https://docs.fastht.ml/explains/faq.html)
- [x] I have provided a minimal reproducible example
- [x] I have included the versions of fastlite, fastcore, and fasthtml
- [x] I understand that this is a volunteer open source project with no commercial support.

**Comment by pydanny** [comment]
@Artem-Ter, I can't replicate your error, see my review of your bug report here: https://gist.github.com/pydanny/6e57acc3c1afa9b20b02d989714f3d97

For what it's worth, as we've replaced the use of the Python stdlib sqlite3 with APSW, your reported error might no longer be valid. Please let me know if this error is still real, as I might have made a mistake in my review.

**Comment by Artem-Ter** [comment]
@pydanny , thank you for your feedback.
I tried to run this case on new version of FastHTML - it worked fine. So probably you can close this issue

P.S. For the package 0.6.10, if i add defaults or not_null, it is still throwing TypeError, see below:
```
File "/home/alter/Dev/retha_crm/mysettings.py", line 290, in _initialize_db
    users.create(
  File "/home/alter/Dev/retha_crm/venv/lib/python3.12/site-packages/fastlite/kw.py", line 89, in create
    return self._orig_create(
           ^^^^^^^^^^^^^^^^^^
  File "/home/alter/Dev/retha_crm/venv/lib/python3.12/site-packages/sqlite_minutils/db.py", line 1626, in create
    self.db.create_table(
  File "/home/alter/Dev/retha_crm/venv/lib/python3.12/site-packages/sqlite_minutils/db.py", line 992, in create_table
    created_table = self.table(
                    ^^^^^^^^^^^
  File "/home/alter/Dev/retha_crm/venv/lib/python3.12/site-packages/sqlite_minutils/db.py", line 456, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```
