### ISSUE TITLE
Link pointing to the wrong URL

### ISSUE THREAD

**Issue by dylanjcastillo** [AnswerDotAI/fasthtml#56]
Hi there,

Amazing stuff as usual @jph00.

Kind of an insignificant issue, but I noticed that this link is pointing to the wrong place:

<img width="338" alt="image" src="https://github.com/user-attachments/assets/135d6750-6f25-4167-804e-a150984f48bd">

I think it should be http://fhdocs.answer.ai/.

Also, the fhdocs link leads to a HTTP version of the site:

<img width="488" alt="image" src="https://github.com/user-attachments/assets/1a28188a-69f2-46d5-bb96-6acb3a3dd2bb">

If you visit the URL using https:// it works correctly, so I think you might just be missing something in the redirect from https://answerdotai.github.io/fasthtml/ or enforcing HTTPS in GitHub Pages.

Thank you for all the great work you make available to the community for free.

**Comment by jph00** [comment]
Thank you @dylanjcastillo -- once the release is done we'll have a site up on that domain.

The ssl issue is due to some conflict between firefox and cloudflare's proxy. I'm not sure how to fit it. It works correctly in Chrome.

**Comment by jph00** [comment]
Ah just found a cloudflare setting which seems to have fixed the firefox problem.
