### ISSUE TITLE
[BUG] Incorrect hx-post Value Breaks File Upload in Example

### ISSUE THREAD

**Issue by plops** [AnswerDotAI/fasthtml#584]
In the example code 'Single File Uploads' and 'Multiple File Uploads' is not working for me.

The hx-post attribute in the file upload form is incorrectly populated with the Python function object representation instead of the function name string "upload", causing htmx to fail processing the form submission.

**Minimal Reproducible Example**
```python
# This is a copy of the non-working code from here https://docs.fastht.ml/tutorials/quickstart_for_web_devs.html
from fasthtml.common import *
from pathlib import Path

app, rt = fast_app()

upload_dir = Path("filez")
upload_dir.mkdir(exist_ok=True)

@rt('/')
def get():
    return Titled("File Upload Demo",
        Article(
# The following line should contain hx_post="upload" 
            Form(hx_post=upload, hx_target="#result-one")(
                Input(type="file", name="file"),
                Button("Upload", type="submit", cls='secondary'),
            ),
            Div(id="result-one")
        )
    )

def FileMetaDataCard(file):
    return Article(
        Header(H3(file.filename)),
        Ul(
            Li('Size: ', file.size),            
            Li('Content Type: ', file.content_type),
            Li('Headers: ', file.headers),
        )
    )    

@rt
async def upload(file: UploadFile):
    card = FileMetaDataCard(file)
    filebuffer = await file.read()
    (upload_dir / file.filename).write_bytes(filebuffer)
    return card

serve()
```

**Expected behavior**
The generated HTML should contain hx-post="upload", allowing htmx to correctly submit the form to the /upload route.

**Actual Behavior:** hx-post="<function upload at 0x...>"

**Environment Information**
Please provide the following version information:
- fastlite version: 23993b133c843ae5ada63e5a72bfd22bd822301d
- fastcore version: 00de908bb27c589dd1723efcb80512ebee00c4d3
- fasthtml version: 61ecb093b4e4b4ef46d180e38e6258073651ef31

**Confirmation**
Please confirm the following:
- [X] I have read the FAQ (https://docs.fastht.ml/explains/faq.html)
- [X] I have provided a minimal reproducible example
- [X] I have included the versions of fastlite, fastcore, and fasthtml
- [X] I understand that this is a volunteer open source project with no commercial support.

**Additional context**

**Affected File:** nbs/tutorials/quickstart_for_web_devs.ipynb (likely the only file needing changes, though nbs/llms-ctx-full.txt and nbs/llms-ctx.txt contain the related function).

I think two code examples 'Single File Uploads' and 'Multiple File Uploads' have this issue.

**Comment by TransparentIA** [comment]
Hi plops,
I can reproduce the issue with FastHTML version '0.9.1'.
Odd enough, it works in a Jupyter notebook.
So, I found that specifying the host in the python script works again:
serve(host='localhost')
It might be that '0.0.0.0' is not converted to 'localhost' ?

**Comment by plops** [comment]
@TransparentIA  this observation intrigued me, so I tried myself.

For me adding the option host='localhost' to the serve() call doesn't fix the issue.


```python
serve()
# => INFO:     127.0.0.1:58928 - "POST /%3Cfunction%20upload%20at%200x7f24d96ccea0%3E HTTP/1.1" 404 Not Found


serve(host='localhost')
# => INFO:     127.0.0.1:53432 - "POST /%3Cfunction%20upload%20at%200x7fe87a4c8f40%3E HTTP/1.1" 404 Not Found

# The proper fix:
Form(hx_post="upload", hx_target="#result-one") ... 
serve()
# => INFO:     127.0.0.1:49164 - "POST /upload HTTP/1.1" 200 OK

```

Note that I added the relevant lines from the log output after # =>

**Comment by jph00** [comment]
I believe this should be fixed now in the latest - please reopen if you can still repro it.
