### ISSUE TITLE
Link Display config error - http://0.0.0.0:5001 not http://localhost:5001

### ISSUE THREAD

**Issue by djslash9** [AnswerDotAI/fasthtml#596]
INFO:     Will watch for changes in these directories: ['E:\\Python\\fasthtml\\project01']
INFO:     Uvicorn running on http://0.0.0.0:5001 (Press CTRL+C to quit)
INFO:     Started reloader process [17912] using WatchFiles
INFO:     Started server process [15452]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:52865 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:52865 - "GET /favicon.ico HTTP/1.1" 404 Not Found

**Comment by jph00** [comment]
If you run `serve` it shows localhost above that.
