### ISSUE TITLE
mixed use of FastHTML and fast_app in tutorial - can we standardize to fast_app everywhere? 

### ISSUE THREAD

**Issue by siraj-samsudeen** [AnswerDotAI/fasthtml#609]
This intro page uses fast_app
https://docs.fastht.ml/

This page uses FastHTML and then app.get rather than rt which was used in the main docs page above. 
https://docs.fastht.ml/tutorials/by_example.html

I would like to help standardize this, but I could not figure out where the files related to the tutorial pages live in the GitHub rep. If someone can point me to it, I can send a PR with the proposed changes.

**Comment by jamilraichouni** [comment]
Note, that there are oeple who prefer the decorators `app.get`, `app.post` etc. because of the use of mypy.

**Comment by JohnYeung-dojjy** [comment]
Speaking of app.get, could the fasthtml team change the implementation in core.py from
```python
all_meths = 'get post put delete patch head trace options'.split()
for o in all_meths: setattr(FastHTML, o, partialmethod(FastHTML.route, methods=o))
```
to simply
```
FastHTML.get = partialmethod(FastHTML.route, methods="get")
FastHTML.post = partialmethod(FastHTML.route, methods="post")
...
```
It breaks the linting

**Comment by jph00** [comment]
There isn't a standard - there are different features for different people and we like to show them all.

We're not making our code more complicated to help broken linters.
