### ISSUE TITLE
Hello World Fails with missing dependency.

### ISSUE THREAD

**Issue by JoeBrig** [AnswerDotAI/fasthtml#614]
/venv/lib/python3.13/site-packages/fasthtml/common.py", line 7, in <module>
    from sqlite_minutils import Database
ModuleNotFoundError: No module named 'sqlite_minutils'

I can manually install this, but doesn't give confidence. 

pip show python-fasthtml

Name: python-fasthtml
Version: 0.10.2
Summary: The fastest way to create an HTML app
Home-page: https://github.com/AnswerDotAI/fasthtml
Author: Jeremy Howard and contributors
Author-email: github@jhoward.fastmail.fm
License: Apache Software License 2.0
Location: /Users/slim/dev/tmp/uv2/venv/lib/python3.13/site-packages
Requires: beautifulsoup4, fastcore, fastlite, httpx, itsdangerous, oauthlib, python-dateutil, python-multipart, starlette, uvicorn
Required-by:

**Comment by jph00** [comment]
Fixed in 0.10.3.
