### ISSUE TITLE
What is purpose of `examples/impl.ipynb` and `examples/impl.ipynb`?

### ISSUE THREAD

**Issue by pydanny** [AnswerDotAI/fasthtml#65]
Do we need these modules?

**Comment by jph00** [comment]
Probably not - it was just me experimenting with showing how to generate fasthtml apps from notebooks. But I think @ncoop57's recent work probably obsoletes it; is that right Nate?

**Comment by ncoop57** [comment]
I haven't made any tutorial on how to write a fasthtml app from a notebook. I think we haven't figured it out ourselves to be honest so I'd lean towards not promoting that workflow until we or the community figures out a better method.
