### ISSUE TITLE
Tasks for blog tutorial

### ISSUE THREAD

**Issue by pydanny** [AnswerDotAI/fasthtml#75]
- [x] Intro
- [x] Minimal view
- [x] `*args` trick for building out content
- [ ] Read files from disk
- [ ] List articles view
- [ ] YAML parsing
- [ ] Markdown formatting
- [ ] Detail view
- [ ] RSS feed
- [ ] Pages independent of the list of articles (about and contact come to mind)
- [ ] Import and Export of articles
- [ ] Tagging and categorization of data
- [ ] Deployment
- [ ] Ability to scale for large volumes of readers (caching)
- [ ] Migrate to database
- [ ] Authentication
- [ ] Socials
- [ ] Favicon
- [ ] Web form for data controls
- [ ] Tests

**Comment by bryanwhiting** [comment]
+1 excited for this!

**Comment by CodyBontecou** [comment]
Form validation within the web form section would be a good addition.

**Comment by Isaac-Flath** [comment]
@pydanny I'd love to write something to include for rendering Jupyter Notebooks as blog posts as a second format to markdown.  I think it would loop through the cells in the JSON and have each rendered based on the cell type.  

+ Markdown cells -> Rendered with MarkdownJS
+ Code Cells -> Rendered with  HighlightJS
+ Cell Output -> TBD, probably depends on what the output is

I can also do this as a separate blog post that builds on this tutorial if that's better.
