### ISSUE TITLE
how to encapsulate request function into class?

### ISSUE THREAD

**Issue by fanfeilong** [AnswerDotAI/fasthtml#96]
I've used Flask, and Flask's blueprints enable to encapsulate http request into class method, for example

```python
class API:
  def __init__(self):
    self.blueprint = Blueprint('test', __name__)
  
  def setup(self):
    @self.blue_print.route('/xxx/', methods=['POST'])
    def xxx():
      ...
    
    @self.blue_print.route('/yyy/', methods=['POST'])
    def yyy():
      ...
```

when the server growth, this is useful for code modular, does the `fasthtml` has similar component?

**Comment by jph00** [comment]
Yes you can add decorated functions anywhere you like.

**Comment by fanfeilong** [comment]
> Yes you can add decorated functions anywhere you like.

that's great! i will try!
