### ISSUE TITLE
cant run http://0.0.0.0:5001

### ISSUE THREAD

**Issue by roohe** [AnswerDotAI/fasthtml#97]
cant run http://0.0.0.0:5001 I must manually changed it to http://localhost:5001/ to run it

**Comment by mborus** [comment]
> cant run http://0.0.0.0:5001 I must manually changed it to http://localhost:5001/ to run it

Usually if you run any web server on "0.0.0.0", it means that outside machines can access it as well.
If you run it on "127.0.0.1", it is not visible outside of your computer.

You'll still have to connect to "http://127.0.0.1:5001" or ""http://localhost:5001" to use it.

**Comment by SepineTam** [comment]
So, why 0.0.0.0 is not work, but 127.0.0.1 is right. is there some knowledge?
